
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `App` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model App
 * 
 */
export type AppModel = runtime.Types.Result.DefaultSelection<Prisma.$AppPayload>

export type AggregateApp = {
  _count: AppCountAggregateOutputType | null
  _min: AppMinAggregateOutputType | null
  _max: AppMaxAggregateOutputType | null
}

export type AppMinAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  type: $Enums.AppType | null
  name: string | null
  slug: string | null
  isFree: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppMaxAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  type: $Enums.AppType | null
  name: string | null
  slug: string | null
  isFree: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppCountAggregateOutputType = {
  id: number
  workspaceId: number
  type: number
  name: number
  slug: number
  isFree: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AppMinAggregateInputType = {
  id?: true
  workspaceId?: true
  type?: true
  name?: true
  slug?: true
  isFree?: true
  createdAt?: true
  updatedAt?: true
}

export type AppMaxAggregateInputType = {
  id?: true
  workspaceId?: true
  type?: true
  name?: true
  slug?: true
  isFree?: true
  createdAt?: true
  updatedAt?: true
}

export type AppCountAggregateInputType = {
  id?: true
  workspaceId?: true
  type?: true
  name?: true
  slug?: true
  isFree?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AppAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which App to aggregate.
   */
  where?: Prisma.AppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apps to fetch.
   */
  orderBy?: Prisma.AppOrderByWithRelationInput | Prisma.AppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Apps
  **/
  _count?: true | AppCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppMaxAggregateInputType
}

export type GetAppAggregateType<T extends AppAggregateArgs> = {
      [P in keyof T & keyof AggregateApp]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApp[P]>
    : Prisma.GetScalarType<T[P], AggregateApp[P]>
}




export type AppGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppWhereInput
  orderBy?: Prisma.AppOrderByWithAggregationInput | Prisma.AppOrderByWithAggregationInput[]
  by: Prisma.AppScalarFieldEnum[] | Prisma.AppScalarFieldEnum
  having?: Prisma.AppScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppCountAggregateInputType | true
  _min?: AppMinAggregateInputType
  _max?: AppMaxAggregateInputType
}

export type AppGroupByOutputType = {
  id: string
  workspaceId: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree: boolean
  createdAt: Date
  updatedAt: Date
  _count: AppCountAggregateOutputType | null
  _min: AppMinAggregateOutputType | null
  _max: AppMaxAggregateOutputType | null
}

type GetAppGroupByPayload<T extends AppGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppGroupByOutputType[P]>
      }
    >
  >



export type AppWhereInput = {
  AND?: Prisma.AppWhereInput | Prisma.AppWhereInput[]
  OR?: Prisma.AppWhereInput[]
  NOT?: Prisma.AppWhereInput | Prisma.AppWhereInput[]
  id?: Prisma.StringFilter<"App"> | string
  workspaceId?: Prisma.StringFilter<"App"> | string
  type?: Prisma.EnumAppTypeFilter<"App"> | $Enums.AppType
  name?: Prisma.StringFilter<"App"> | string
  slug?: Prisma.StringFilter<"App"> | string
  isFree?: Prisma.BoolFilter<"App"> | boolean
  createdAt?: Prisma.DateTimeFilter<"App"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"App"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  courseProfile?: Prisma.XOR<Prisma.AppCourseProfileNullableScalarRelationFilter, Prisma.AppCourseProfileWhereInput> | null
  paymentIntegration?: Prisma.XOR<Prisma.AppPaymentIntegrationNullableScalarRelationFilter, Prisma.AppPaymentIntegrationWhereInput> | null
  emailChallenges?: Prisma.EmailChallengeListRelationFilter
  customerSessions?: Prisma.CustomerSessionListRelationFilter
}

export type AppOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  isFree?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
  courseProfile?: Prisma.AppCourseProfileOrderByWithRelationInput
  paymentIntegration?: Prisma.AppPaymentIntegrationOrderByWithRelationInput
  emailChallenges?: Prisma.EmailChallengeOrderByRelationAggregateInput
  customerSessions?: Prisma.CustomerSessionOrderByRelationAggregateInput
}

export type AppWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.AppWhereInput | Prisma.AppWhereInput[]
  OR?: Prisma.AppWhereInput[]
  NOT?: Prisma.AppWhereInput | Prisma.AppWhereInput[]
  workspaceId?: Prisma.StringFilter<"App"> | string
  type?: Prisma.EnumAppTypeFilter<"App"> | $Enums.AppType
  name?: Prisma.StringFilter<"App"> | string
  isFree?: Prisma.BoolFilter<"App"> | boolean
  createdAt?: Prisma.DateTimeFilter<"App"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"App"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  courseProfile?: Prisma.XOR<Prisma.AppCourseProfileNullableScalarRelationFilter, Prisma.AppCourseProfileWhereInput> | null
  paymentIntegration?: Prisma.XOR<Prisma.AppPaymentIntegrationNullableScalarRelationFilter, Prisma.AppPaymentIntegrationWhereInput> | null
  emailChallenges?: Prisma.EmailChallengeListRelationFilter
  customerSessions?: Prisma.CustomerSessionListRelationFilter
}, "id" | "slug">

export type AppOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  isFree?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AppCountOrderByAggregateInput
  _max?: Prisma.AppMaxOrderByAggregateInput
  _min?: Prisma.AppMinOrderByAggregateInput
}

export type AppScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppScalarWhereWithAggregatesInput | Prisma.AppScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppScalarWhereWithAggregatesInput | Prisma.AppScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"App"> | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"App"> | string
  type?: Prisma.EnumAppTypeWithAggregatesFilter<"App"> | $Enums.AppType
  name?: Prisma.StringWithAggregatesFilter<"App"> | string
  slug?: Prisma.StringWithAggregatesFilter<"App"> | string
  isFree?: Prisma.BoolWithAggregatesFilter<"App"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"App"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"App"> | Date | string
}

export type AppCreateInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutAppsInput
  courseProfile?: Prisma.AppCourseProfileCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionCreateNestedManyWithoutAppInput
}

export type AppUncheckedCreateInput = {
  id?: string
  workspaceId: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeUncheckedCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutAppInput
}

export type AppUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutAppsNestedInput
  courseProfile?: Prisma.AppCourseProfileUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUpdateManyWithoutAppNestedInput
}

export type AppUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUncheckedUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutAppNestedInput
}

export type AppCreateManyInput = {
  id?: string
  workspaceId: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppNullableScalarRelationFilter = {
  is?: Prisma.AppWhereInput | null
  isNot?: Prisma.AppWhereInput | null
}

export type AppListRelationFilter = {
  every?: Prisma.AppWhereInput
  some?: Prisma.AppWhereInput
  none?: Prisma.AppWhereInput
}

export type AppOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AppCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  isFree?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  isFree?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  isFree?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppScalarRelationFilter = {
  is?: Prisma.AppWhereInput
  isNot?: Prisma.AppWhereInput
}

export type AppCreateNestedOneWithoutEmailChallengesInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutEmailChallengesInput, Prisma.AppUncheckedCreateWithoutEmailChallengesInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutEmailChallengesInput
  connect?: Prisma.AppWhereUniqueInput
}

export type AppUpdateOneWithoutEmailChallengesNestedInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutEmailChallengesInput, Prisma.AppUncheckedCreateWithoutEmailChallengesInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutEmailChallengesInput
  upsert?: Prisma.AppUpsertWithoutEmailChallengesInput
  disconnect?: Prisma.AppWhereInput | boolean
  delete?: Prisma.AppWhereInput | boolean
  connect?: Prisma.AppWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppUpdateToOneWithWhereWithoutEmailChallengesInput, Prisma.AppUpdateWithoutEmailChallengesInput>, Prisma.AppUncheckedUpdateWithoutEmailChallengesInput>
}

export type AppCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutWorkspaceInput, Prisma.AppUncheckedCreateWithoutWorkspaceInput> | Prisma.AppCreateWithoutWorkspaceInput[] | Prisma.AppUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutWorkspaceInput | Prisma.AppCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.AppCreateManyWorkspaceInputEnvelope
  connect?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
}

export type AppUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutWorkspaceInput, Prisma.AppUncheckedCreateWithoutWorkspaceInput> | Prisma.AppCreateWithoutWorkspaceInput[] | Prisma.AppUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutWorkspaceInput | Prisma.AppCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.AppCreateManyWorkspaceInputEnvelope
  connect?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
}

export type AppUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutWorkspaceInput, Prisma.AppUncheckedCreateWithoutWorkspaceInput> | Prisma.AppCreateWithoutWorkspaceInput[] | Prisma.AppUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutWorkspaceInput | Prisma.AppCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.AppUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.AppUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.AppCreateManyWorkspaceInputEnvelope
  set?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  disconnect?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  delete?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  connect?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  update?: Prisma.AppUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.AppUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.AppUpdateManyWithWhereWithoutWorkspaceInput | Prisma.AppUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.AppScalarWhereInput | Prisma.AppScalarWhereInput[]
}

export type AppUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutWorkspaceInput, Prisma.AppUncheckedCreateWithoutWorkspaceInput> | Prisma.AppCreateWithoutWorkspaceInput[] | Prisma.AppUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutWorkspaceInput | Prisma.AppCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.AppUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.AppUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.AppCreateManyWorkspaceInputEnvelope
  set?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  disconnect?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  delete?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  connect?: Prisma.AppWhereUniqueInput | Prisma.AppWhereUniqueInput[]
  update?: Prisma.AppUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.AppUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.AppUpdateManyWithWhereWithoutWorkspaceInput | Prisma.AppUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.AppScalarWhereInput | Prisma.AppScalarWhereInput[]
}

export type EnumAppTypeFieldUpdateOperationsInput = {
  set?: $Enums.AppType
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type AppCreateNestedOneWithoutCourseProfileInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutCourseProfileInput, Prisma.AppUncheckedCreateWithoutCourseProfileInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutCourseProfileInput
  connect?: Prisma.AppWhereUniqueInput
}

export type AppUpdateOneRequiredWithoutCourseProfileNestedInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutCourseProfileInput, Prisma.AppUncheckedCreateWithoutCourseProfileInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutCourseProfileInput
  upsert?: Prisma.AppUpsertWithoutCourseProfileInput
  connect?: Prisma.AppWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppUpdateToOneWithWhereWithoutCourseProfileInput, Prisma.AppUpdateWithoutCourseProfileInput>, Prisma.AppUncheckedUpdateWithoutCourseProfileInput>
}

export type AppCreateNestedOneWithoutPaymentIntegrationInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutPaymentIntegrationInput, Prisma.AppUncheckedCreateWithoutPaymentIntegrationInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutPaymentIntegrationInput
  connect?: Prisma.AppWhereUniqueInput
}

export type AppUpdateOneRequiredWithoutPaymentIntegrationNestedInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutPaymentIntegrationInput, Prisma.AppUncheckedCreateWithoutPaymentIntegrationInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutPaymentIntegrationInput
  upsert?: Prisma.AppUpsertWithoutPaymentIntegrationInput
  connect?: Prisma.AppWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppUpdateToOneWithWhereWithoutPaymentIntegrationInput, Prisma.AppUpdateWithoutPaymentIntegrationInput>, Prisma.AppUncheckedUpdateWithoutPaymentIntegrationInput>
}

export type AppCreateNestedOneWithoutCustomerSessionsInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutCustomerSessionsInput, Prisma.AppUncheckedCreateWithoutCustomerSessionsInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutCustomerSessionsInput
  connect?: Prisma.AppWhereUniqueInput
}

export type AppUpdateOneRequiredWithoutCustomerSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.AppCreateWithoutCustomerSessionsInput, Prisma.AppUncheckedCreateWithoutCustomerSessionsInput>
  connectOrCreate?: Prisma.AppCreateOrConnectWithoutCustomerSessionsInput
  upsert?: Prisma.AppUpsertWithoutCustomerSessionsInput
  connect?: Prisma.AppWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppUpdateToOneWithWhereWithoutCustomerSessionsInput, Prisma.AppUpdateWithoutCustomerSessionsInput>, Prisma.AppUncheckedUpdateWithoutCustomerSessionsInput>
}

export type AppCreateWithoutEmailChallengesInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutAppsInput
  courseProfile?: Prisma.AppCourseProfileCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationCreateNestedOneWithoutAppInput
  customerSessions?: Prisma.CustomerSessionCreateNestedManyWithoutAppInput
}

export type AppUncheckedCreateWithoutEmailChallengesInput = {
  id?: string
  workspaceId: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedCreateNestedOneWithoutAppInput
  customerSessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutAppInput
}

export type AppCreateOrConnectWithoutEmailChallengesInput = {
  where: Prisma.AppWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCreateWithoutEmailChallengesInput, Prisma.AppUncheckedCreateWithoutEmailChallengesInput>
}

export type AppUpsertWithoutEmailChallengesInput = {
  update: Prisma.XOR<Prisma.AppUpdateWithoutEmailChallengesInput, Prisma.AppUncheckedUpdateWithoutEmailChallengesInput>
  create: Prisma.XOR<Prisma.AppCreateWithoutEmailChallengesInput, Prisma.AppUncheckedCreateWithoutEmailChallengesInput>
  where?: Prisma.AppWhereInput
}

export type AppUpdateToOneWithWhereWithoutEmailChallengesInput = {
  where?: Prisma.AppWhereInput
  data: Prisma.XOR<Prisma.AppUpdateWithoutEmailChallengesInput, Prisma.AppUncheckedUpdateWithoutEmailChallengesInput>
}

export type AppUpdateWithoutEmailChallengesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutAppsNestedInput
  courseProfile?: Prisma.AppCourseProfileUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUpdateOneWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUpdateManyWithoutAppNestedInput
}

export type AppUncheckedUpdateWithoutEmailChallengesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedUpdateOneWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutAppNestedInput
}

export type AppCreateWithoutWorkspaceInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  courseProfile?: Prisma.AppCourseProfileCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionCreateNestedManyWithoutAppInput
}

export type AppUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeUncheckedCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutAppInput
}

export type AppCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.AppWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCreateWithoutWorkspaceInput, Prisma.AppUncheckedCreateWithoutWorkspaceInput>
}

export type AppCreateManyWorkspaceInputEnvelope = {
  data: Prisma.AppCreateManyWorkspaceInput | Prisma.AppCreateManyWorkspaceInput[]
  skipDuplicates?: boolean
}

export type AppUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.AppWhereUniqueInput
  update: Prisma.XOR<Prisma.AppUpdateWithoutWorkspaceInput, Prisma.AppUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.AppCreateWithoutWorkspaceInput, Prisma.AppUncheckedCreateWithoutWorkspaceInput>
}

export type AppUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.AppWhereUniqueInput
  data: Prisma.XOR<Prisma.AppUpdateWithoutWorkspaceInput, Prisma.AppUncheckedUpdateWithoutWorkspaceInput>
}

export type AppUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.AppScalarWhereInput
  data: Prisma.XOR<Prisma.AppUpdateManyMutationInput, Prisma.AppUncheckedUpdateManyWithoutWorkspaceInput>
}

export type AppScalarWhereInput = {
  AND?: Prisma.AppScalarWhereInput | Prisma.AppScalarWhereInput[]
  OR?: Prisma.AppScalarWhereInput[]
  NOT?: Prisma.AppScalarWhereInput | Prisma.AppScalarWhereInput[]
  id?: Prisma.StringFilter<"App"> | string
  workspaceId?: Prisma.StringFilter<"App"> | string
  type?: Prisma.EnumAppTypeFilter<"App"> | $Enums.AppType
  name?: Prisma.StringFilter<"App"> | string
  slug?: Prisma.StringFilter<"App"> | string
  isFree?: Prisma.BoolFilter<"App"> | boolean
  createdAt?: Prisma.DateTimeFilter<"App"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"App"> | Date | string
}

export type AppCreateWithoutCourseProfileInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutAppsInput
  paymentIntegration?: Prisma.AppPaymentIntegrationCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionCreateNestedManyWithoutAppInput
}

export type AppUncheckedCreateWithoutCourseProfileInput = {
  id?: string
  workspaceId: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeUncheckedCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutAppInput
}

export type AppCreateOrConnectWithoutCourseProfileInput = {
  where: Prisma.AppWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCreateWithoutCourseProfileInput, Prisma.AppUncheckedCreateWithoutCourseProfileInput>
}

export type AppUpsertWithoutCourseProfileInput = {
  update: Prisma.XOR<Prisma.AppUpdateWithoutCourseProfileInput, Prisma.AppUncheckedUpdateWithoutCourseProfileInput>
  create: Prisma.XOR<Prisma.AppCreateWithoutCourseProfileInput, Prisma.AppUncheckedCreateWithoutCourseProfileInput>
  where?: Prisma.AppWhereInput
}

export type AppUpdateToOneWithWhereWithoutCourseProfileInput = {
  where?: Prisma.AppWhereInput
  data: Prisma.XOR<Prisma.AppUpdateWithoutCourseProfileInput, Prisma.AppUncheckedUpdateWithoutCourseProfileInput>
}

export type AppUpdateWithoutCourseProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutAppsNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUpdateManyWithoutAppNestedInput
}

export type AppUncheckedUpdateWithoutCourseProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUncheckedUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutAppNestedInput
}

export type AppCreateWithoutPaymentIntegrationInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutAppsInput
  courseProfile?: Prisma.AppCourseProfileCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionCreateNestedManyWithoutAppInput
}

export type AppUncheckedCreateWithoutPaymentIntegrationInput = {
  id?: string
  workspaceId: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeUncheckedCreateNestedManyWithoutAppInput
  customerSessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutAppInput
}

export type AppCreateOrConnectWithoutPaymentIntegrationInput = {
  where: Prisma.AppWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCreateWithoutPaymentIntegrationInput, Prisma.AppUncheckedCreateWithoutPaymentIntegrationInput>
}

export type AppUpsertWithoutPaymentIntegrationInput = {
  update: Prisma.XOR<Prisma.AppUpdateWithoutPaymentIntegrationInput, Prisma.AppUncheckedUpdateWithoutPaymentIntegrationInput>
  create: Prisma.XOR<Prisma.AppCreateWithoutPaymentIntegrationInput, Prisma.AppUncheckedCreateWithoutPaymentIntegrationInput>
  where?: Prisma.AppWhereInput
}

export type AppUpdateToOneWithWhereWithoutPaymentIntegrationInput = {
  where?: Prisma.AppWhereInput
  data: Prisma.XOR<Prisma.AppUpdateWithoutPaymentIntegrationInput, Prisma.AppUncheckedUpdateWithoutPaymentIntegrationInput>
}

export type AppUpdateWithoutPaymentIntegrationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutAppsNestedInput
  courseProfile?: Prisma.AppCourseProfileUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUpdateManyWithoutAppNestedInput
}

export type AppUncheckedUpdateWithoutPaymentIntegrationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUncheckedUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutAppNestedInput
}

export type AppCreateWithoutCustomerSessionsInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutAppsInput
  courseProfile?: Prisma.AppCourseProfileCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeCreateNestedManyWithoutAppInput
}

export type AppUncheckedCreateWithoutCustomerSessionsInput = {
  id?: string
  workspaceId: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedCreateNestedOneWithoutAppInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedCreateNestedOneWithoutAppInput
  emailChallenges?: Prisma.EmailChallengeUncheckedCreateNestedManyWithoutAppInput
}

export type AppCreateOrConnectWithoutCustomerSessionsInput = {
  where: Prisma.AppWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCreateWithoutCustomerSessionsInput, Prisma.AppUncheckedCreateWithoutCustomerSessionsInput>
}

export type AppUpsertWithoutCustomerSessionsInput = {
  update: Prisma.XOR<Prisma.AppUpdateWithoutCustomerSessionsInput, Prisma.AppUncheckedUpdateWithoutCustomerSessionsInput>
  create: Prisma.XOR<Prisma.AppCreateWithoutCustomerSessionsInput, Prisma.AppUncheckedCreateWithoutCustomerSessionsInput>
  where?: Prisma.AppWhereInput
}

export type AppUpdateToOneWithWhereWithoutCustomerSessionsInput = {
  where?: Prisma.AppWhereInput
  data: Prisma.XOR<Prisma.AppUpdateWithoutCustomerSessionsInput, Prisma.AppUncheckedUpdateWithoutCustomerSessionsInput>
}

export type AppUpdateWithoutCustomerSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutAppsNestedInput
  courseProfile?: Prisma.AppCourseProfileUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUpdateManyWithoutAppNestedInput
}

export type AppUncheckedUpdateWithoutCustomerSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUncheckedUpdateManyWithoutAppNestedInput
}

export type AppCreateManyWorkspaceInput = {
  id?: string
  type: $Enums.AppType
  name: string
  slug: string
  isFree?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courseProfile?: Prisma.AppCourseProfileUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUpdateManyWithoutAppNestedInput
}

export type AppUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courseProfile?: Prisma.AppCourseProfileUncheckedUpdateOneWithoutAppNestedInput
  paymentIntegration?: Prisma.AppPaymentIntegrationUncheckedUpdateOneWithoutAppNestedInput
  emailChallenges?: Prisma.EmailChallengeUncheckedUpdateManyWithoutAppNestedInput
  customerSessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutAppNestedInput
}

export type AppUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumAppTypeFieldUpdateOperationsInput | $Enums.AppType
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  isFree?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AppCountOutputType
 */

export type AppCountOutputType = {
  emailChallenges: number
  customerSessions: number
}

export type AppCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  emailChallenges?: boolean | AppCountOutputTypeCountEmailChallengesArgs
  customerSessions?: boolean | AppCountOutputTypeCountCustomerSessionsArgs
}

/**
 * AppCountOutputType without action
 */
export type AppCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCountOutputType
   */
  select?: Prisma.AppCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AppCountOutputType without action
 */
export type AppCountOutputTypeCountEmailChallengesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailChallengeWhereInput
}

/**
 * AppCountOutputType without action
 */
export type AppCountOutputTypeCountCustomerSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomerSessionWhereInput
}


export type AppSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  type?: boolean
  name?: boolean
  slug?: boolean
  isFree?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  courseProfile?: boolean | Prisma.App$courseProfileArgs<ExtArgs>
  paymentIntegration?: boolean | Prisma.App$paymentIntegrationArgs<ExtArgs>
  emailChallenges?: boolean | Prisma.App$emailChallengesArgs<ExtArgs>
  customerSessions?: boolean | Prisma.App$customerSessionsArgs<ExtArgs>
  _count?: boolean | Prisma.AppCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["app"]>

export type AppSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  type?: boolean
  name?: boolean
  slug?: boolean
  isFree?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["app"]>

export type AppSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  type?: boolean
  name?: boolean
  slug?: boolean
  isFree?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["app"]>

export type AppSelectScalar = {
  id?: boolean
  workspaceId?: boolean
  type?: boolean
  name?: boolean
  slug?: boolean
  isFree?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AppOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workspaceId" | "type" | "name" | "slug" | "isFree" | "createdAt" | "updatedAt", ExtArgs["result"]["app"]>
export type AppInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  courseProfile?: boolean | Prisma.App$courseProfileArgs<ExtArgs>
  paymentIntegration?: boolean | Prisma.App$paymentIntegrationArgs<ExtArgs>
  emailChallenges?: boolean | Prisma.App$emailChallengesArgs<ExtArgs>
  customerSessions?: boolean | Prisma.App$customerSessionsArgs<ExtArgs>
  _count?: boolean | Prisma.AppCountOutputTypeDefaultArgs<ExtArgs>
}
export type AppIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}
export type AppIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}

export type $AppPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "App"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
    courseProfile: Prisma.$AppCourseProfilePayload<ExtArgs> | null
    paymentIntegration: Prisma.$AppPaymentIntegrationPayload<ExtArgs> | null
    emailChallenges: Prisma.$EmailChallengePayload<ExtArgs>[]
    customerSessions: Prisma.$CustomerSessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workspaceId: string
    type: $Enums.AppType
    name: string
    slug: string
    isFree: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["app"]>
  composites: {}
}

export type AppGetPayload<S extends boolean | null | undefined | AppDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppPayload, S>

export type AppCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppCountAggregateInputType | true
  }

export interface AppDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['App'], meta: { name: 'App' } }
  /**
   * Find zero or one App that matches the filter.
   * @param {AppFindUniqueArgs} args - Arguments to find a App
   * @example
   * // Get one App
   * const app = await prisma.app.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppFindUniqueArgs>(args: Prisma.SelectSubset<T, AppFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one App that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppFindUniqueOrThrowArgs} args - Arguments to find a App
   * @example
   * // Get one App
   * const app = await prisma.app.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first App that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppFindFirstArgs} args - Arguments to find a App
   * @example
   * // Get one App
   * const app = await prisma.app.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppFindFirstArgs>(args?: Prisma.SelectSubset<T, AppFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first App that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppFindFirstOrThrowArgs} args - Arguments to find a App
   * @example
   * // Get one App
   * const app = await prisma.app.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Apps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Apps
   * const apps = await prisma.app.findMany()
   * 
   * // Get first 10 Apps
   * const apps = await prisma.app.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const appWithIdOnly = await prisma.app.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AppFindManyArgs>(args?: Prisma.SelectSubset<T, AppFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a App.
   * @param {AppCreateArgs} args - Arguments to create a App.
   * @example
   * // Create one App
   * const App = await prisma.app.create({
   *   data: {
   *     // ... data to create a App
   *   }
   * })
   * 
   */
  create<T extends AppCreateArgs>(args: Prisma.SelectSubset<T, AppCreateArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Apps.
   * @param {AppCreateManyArgs} args - Arguments to create many Apps.
   * @example
   * // Create many Apps
   * const app = await prisma.app.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppCreateManyArgs>(args?: Prisma.SelectSubset<T, AppCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Apps and returns the data saved in the database.
   * @param {AppCreateManyAndReturnArgs} args - Arguments to create many Apps.
   * @example
   * // Create many Apps
   * const app = await prisma.app.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Apps and only return the `id`
   * const appWithIdOnly = await prisma.app.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a App.
   * @param {AppDeleteArgs} args - Arguments to delete one App.
   * @example
   * // Delete one App
   * const App = await prisma.app.delete({
   *   where: {
   *     // ... filter to delete one App
   *   }
   * })
   * 
   */
  delete<T extends AppDeleteArgs>(args: Prisma.SelectSubset<T, AppDeleteArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one App.
   * @param {AppUpdateArgs} args - Arguments to update one App.
   * @example
   * // Update one App
   * const app = await prisma.app.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppUpdateArgs>(args: Prisma.SelectSubset<T, AppUpdateArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Apps.
   * @param {AppDeleteManyArgs} args - Arguments to filter Apps to delete.
   * @example
   * // Delete a few Apps
   * const { count } = await prisma.app.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Apps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Apps
   * const app = await prisma.app.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppUpdateManyArgs>(args: Prisma.SelectSubset<T, AppUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Apps and returns the data updated in the database.
   * @param {AppUpdateManyAndReturnArgs} args - Arguments to update many Apps.
   * @example
   * // Update many Apps
   * const app = await prisma.app.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Apps and only return the `id`
   * const appWithIdOnly = await prisma.app.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one App.
   * @param {AppUpsertArgs} args - Arguments to update or create a App.
   * @example
   * // Update or create a App
   * const app = await prisma.app.upsert({
   *   create: {
   *     // ... data to create a App
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the App we want to update
   *   }
   * })
   */
  upsert<T extends AppUpsertArgs>(args: Prisma.SelectSubset<T, AppUpsertArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Apps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCountArgs} args - Arguments to filter Apps to count.
   * @example
   * // Count the number of Apps
   * const count = await prisma.app.count({
   *   where: {
   *     // ... the filter for the Apps we want to count
   *   }
   * })
  **/
  count<T extends AppCountArgs>(
    args?: Prisma.Subset<T, AppCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a App.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppAggregateArgs>(args: Prisma.Subset<T, AppAggregateArgs>): Prisma.PrismaPromise<GetAppAggregateType<T>>

  /**
   * Group by App.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppGroupByArgs['orderBy'] }
      : { orderBy?: AppGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the App model
 */
readonly fields: AppFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for App.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  courseProfile<T extends Prisma.App$courseProfileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.App$courseProfileArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  paymentIntegration<T extends Prisma.App$paymentIntegrationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.App$paymentIntegrationArgs<ExtArgs>>): Prisma.Prisma__AppPaymentIntegrationClient<runtime.Types.Result.GetResult<Prisma.$AppPaymentIntegrationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  emailChallenges<T extends Prisma.App$emailChallengesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.App$emailChallengesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailChallengePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  customerSessions<T extends Prisma.App$customerSessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.App$customerSessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the App model
 */
export interface AppFieldRefs {
  readonly id: Prisma.FieldRef<"App", 'String'>
  readonly workspaceId: Prisma.FieldRef<"App", 'String'>
  readonly type: Prisma.FieldRef<"App", 'AppType'>
  readonly name: Prisma.FieldRef<"App", 'String'>
  readonly slug: Prisma.FieldRef<"App", 'String'>
  readonly isFree: Prisma.FieldRef<"App", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"App", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"App", 'DateTime'>
}
    

// Custom InputTypes
/**
 * App findUnique
 */
export type AppFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * Filter, which App to fetch.
   */
  where: Prisma.AppWhereUniqueInput
}

/**
 * App findUniqueOrThrow
 */
export type AppFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * Filter, which App to fetch.
   */
  where: Prisma.AppWhereUniqueInput
}

/**
 * App findFirst
 */
export type AppFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * Filter, which App to fetch.
   */
  where?: Prisma.AppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apps to fetch.
   */
  orderBy?: Prisma.AppOrderByWithRelationInput | Prisma.AppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Apps.
   */
  cursor?: Prisma.AppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Apps.
   */
  distinct?: Prisma.AppScalarFieldEnum | Prisma.AppScalarFieldEnum[]
}

/**
 * App findFirstOrThrow
 */
export type AppFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * Filter, which App to fetch.
   */
  where?: Prisma.AppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apps to fetch.
   */
  orderBy?: Prisma.AppOrderByWithRelationInput | Prisma.AppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Apps.
   */
  cursor?: Prisma.AppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Apps.
   */
  distinct?: Prisma.AppScalarFieldEnum | Prisma.AppScalarFieldEnum[]
}

/**
 * App findMany
 */
export type AppFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * Filter, which Apps to fetch.
   */
  where?: Prisma.AppWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apps to fetch.
   */
  orderBy?: Prisma.AppOrderByWithRelationInput | Prisma.AppOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Apps.
   */
  cursor?: Prisma.AppWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apps.
   */
  skip?: number
  distinct?: Prisma.AppScalarFieldEnum | Prisma.AppScalarFieldEnum[]
}

/**
 * App create
 */
export type AppCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * The data needed to create a App.
   */
  data: Prisma.XOR<Prisma.AppCreateInput, Prisma.AppUncheckedCreateInput>
}

/**
 * App createMany
 */
export type AppCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Apps.
   */
  data: Prisma.AppCreateManyInput | Prisma.AppCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * App createManyAndReturn
 */
export type AppCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * The data used to create many Apps.
   */
  data: Prisma.AppCreateManyInput | Prisma.AppCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * App update
 */
export type AppUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * The data needed to update a App.
   */
  data: Prisma.XOR<Prisma.AppUpdateInput, Prisma.AppUncheckedUpdateInput>
  /**
   * Choose, which App to update.
   */
  where: Prisma.AppWhereUniqueInput
}

/**
 * App updateMany
 */
export type AppUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Apps.
   */
  data: Prisma.XOR<Prisma.AppUpdateManyMutationInput, Prisma.AppUncheckedUpdateManyInput>
  /**
   * Filter which Apps to update
   */
  where?: Prisma.AppWhereInput
  /**
   * Limit how many Apps to update.
   */
  limit?: number
}

/**
 * App updateManyAndReturn
 */
export type AppUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * The data used to update Apps.
   */
  data: Prisma.XOR<Prisma.AppUpdateManyMutationInput, Prisma.AppUncheckedUpdateManyInput>
  /**
   * Filter which Apps to update
   */
  where?: Prisma.AppWhereInput
  /**
   * Limit how many Apps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * App upsert
 */
export type AppUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * The filter to search for the App to update in case it exists.
   */
  where: Prisma.AppWhereUniqueInput
  /**
   * In case the App found by the `where` argument doesn't exist, create a new App with this data.
   */
  create: Prisma.XOR<Prisma.AppCreateInput, Prisma.AppUncheckedCreateInput>
  /**
   * In case the App was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppUpdateInput, Prisma.AppUncheckedUpdateInput>
}

/**
 * App delete
 */
export type AppDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
  /**
   * Filter which App to delete.
   */
  where: Prisma.AppWhereUniqueInput
}

/**
 * App deleteMany
 */
export type AppDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Apps to delete
   */
  where?: Prisma.AppWhereInput
  /**
   * Limit how many Apps to delete.
   */
  limit?: number
}

/**
 * App.courseProfile
 */
export type App$courseProfileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  where?: Prisma.AppCourseProfileWhereInput
}

/**
 * App.paymentIntegration
 */
export type App$paymentIntegrationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppPaymentIntegration
   */
  select?: Prisma.AppPaymentIntegrationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppPaymentIntegration
   */
  omit?: Prisma.AppPaymentIntegrationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppPaymentIntegrationInclude<ExtArgs> | null
  where?: Prisma.AppPaymentIntegrationWhereInput
}

/**
 * App.emailChallenges
 */
export type App$emailChallengesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailChallenge
   */
  select?: Prisma.EmailChallengeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailChallenge
   */
  omit?: Prisma.EmailChallengeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailChallengeInclude<ExtArgs> | null
  where?: Prisma.EmailChallengeWhereInput
  orderBy?: Prisma.EmailChallengeOrderByWithRelationInput | Prisma.EmailChallengeOrderByWithRelationInput[]
  cursor?: Prisma.EmailChallengeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmailChallengeScalarFieldEnum | Prisma.EmailChallengeScalarFieldEnum[]
}

/**
 * App.customerSessions
 */
export type App$customerSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerSession
   */
  select?: Prisma.CustomerSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerSession
   */
  omit?: Prisma.CustomerSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerSessionInclude<ExtArgs> | null
  where?: Prisma.CustomerSessionWhereInput
  orderBy?: Prisma.CustomerSessionOrderByWithRelationInput | Prisma.CustomerSessionOrderByWithRelationInput[]
  cursor?: Prisma.CustomerSessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CustomerSessionScalarFieldEnum | Prisma.CustomerSessionScalarFieldEnum[]
}

/**
 * App without action
 */
export type AppDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the App
   */
  select?: Prisma.AppSelect<ExtArgs> | null
  /**
   * Omit specific fields from the App
   */
  omit?: Prisma.AppOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppInclude<ExtArgs> | null
}
