
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `AppCustomer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AppCustomer
 * 
 */
export type AppCustomerModel = runtime.Types.Result.DefaultSelection<Prisma.$AppCustomerPayload>

export type AggregateAppCustomer = {
  _count: AppCustomerCountAggregateOutputType | null
  _min: AppCustomerMinAggregateOutputType | null
  _max: AppCustomerMaxAggregateOutputType | null
}

export type AppCustomerMinAggregateOutputType = {
  id: string | null
  appId: string | null
  variantId: string | null
  email: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppCustomerMaxAggregateOutputType = {
  id: string | null
  appId: string | null
  variantId: string | null
  email: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppCustomerCountAggregateOutputType = {
  id: number
  appId: number
  variantId: number
  email: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AppCustomerMinAggregateInputType = {
  id?: true
  appId?: true
  variantId?: true
  email?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type AppCustomerMaxAggregateInputType = {
  id?: true
  appId?: true
  variantId?: true
  email?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type AppCustomerCountAggregateInputType = {
  id?: true
  appId?: true
  variantId?: true
  email?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AppCustomerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppCustomer to aggregate.
   */
  where?: Prisma.AppCustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCustomers to fetch.
   */
  orderBy?: Prisma.AppCustomerOrderByWithRelationInput | Prisma.AppCustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppCustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCustomers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCustomers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AppCustomers
  **/
  _count?: true | AppCustomerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppCustomerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppCustomerMaxAggregateInputType
}

export type GetAppCustomerAggregateType<T extends AppCustomerAggregateArgs> = {
      [P in keyof T & keyof AggregateAppCustomer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppCustomer[P]>
    : Prisma.GetScalarType<T[P], AggregateAppCustomer[P]>
}




export type AppCustomerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppCustomerWhereInput
  orderBy?: Prisma.AppCustomerOrderByWithAggregationInput | Prisma.AppCustomerOrderByWithAggregationInput[]
  by: Prisma.AppCustomerScalarFieldEnum[] | Prisma.AppCustomerScalarFieldEnum
  having?: Prisma.AppCustomerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppCustomerCountAggregateInputType | true
  _min?: AppCustomerMinAggregateInputType
  _max?: AppCustomerMaxAggregateInputType
}

export type AppCustomerGroupByOutputType = {
  id: string
  appId: string
  variantId: string
  email: string
  name: string | null
  createdAt: Date
  updatedAt: Date
  _count: AppCustomerCountAggregateOutputType | null
  _min: AppCustomerMinAggregateOutputType | null
  _max: AppCustomerMaxAggregateOutputType | null
}

type GetAppCustomerGroupByPayload<T extends AppCustomerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppCustomerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppCustomerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppCustomerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppCustomerGroupByOutputType[P]>
      }
    >
  > 



export type AppCustomerWhereInput = {
  AND?: Prisma.AppCustomerWhereInput | Prisma.AppCustomerWhereInput[]
  OR?: Prisma.AppCustomerWhereInput[]
  NOT?: Prisma.AppCustomerWhereInput | Prisma.AppCustomerWhereInput[]
  id?: Prisma.StringFilter<"AppCustomer"> | string
  appId?: Prisma.StringFilter<"AppCustomer"> | string
  variantId?: Prisma.StringFilter<"AppCustomer"> | string
  email?: Prisma.StringFilter<"AppCustomer"> | string
  name?: Prisma.StringNullableFilter<"AppCustomer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AppCustomer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AppCustomer"> | Date | string
  variant?: Prisma.XOR<Prisma.AppVariantScalarRelationFilter, Prisma.AppVariantWhereInput>
  lemonSqueezyCustomer?: Prisma.XOR<Prisma.LemonSqueezyCustomerNullableScalarRelationFilter, Prisma.LemonSqueezyCustomerWhereInput> | null
  sessions?: Prisma.CustomerSessionListRelationFilter
}

export type AppCustomerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  variant?: Prisma.AppVariantOrderByWithRelationInput
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerOrderByWithRelationInput
  sessions?: Prisma.CustomerSessionOrderByRelationAggregateInput
}

export type AppCustomerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AppCustomerWhereInput | Prisma.AppCustomerWhereInput[]
  OR?: Prisma.AppCustomerWhereInput[]
  NOT?: Prisma.AppCustomerWhereInput | Prisma.AppCustomerWhereInput[]
  appId?: Prisma.StringFilter<"AppCustomer"> | string
  variantId?: Prisma.StringFilter<"AppCustomer"> | string
  email?: Prisma.StringFilter<"AppCustomer"> | string
  name?: Prisma.StringNullableFilter<"AppCustomer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AppCustomer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AppCustomer"> | Date | string
  variant?: Prisma.XOR<Prisma.AppVariantScalarRelationFilter, Prisma.AppVariantWhereInput>
  lemonSqueezyCustomer?: Prisma.XOR<Prisma.LemonSqueezyCustomerNullableScalarRelationFilter, Prisma.LemonSqueezyCustomerWhereInput> | null
  sessions?: Prisma.CustomerSessionListRelationFilter
}, "id">

export type AppCustomerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AppCustomerCountOrderByAggregateInput
  _max?: Prisma.AppCustomerMaxOrderByAggregateInput
  _min?: Prisma.AppCustomerMinOrderByAggregateInput
}

export type AppCustomerScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppCustomerScalarWhereWithAggregatesInput | Prisma.AppCustomerScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppCustomerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppCustomerScalarWhereWithAggregatesInput | Prisma.AppCustomerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AppCustomer"> | string
  appId?: Prisma.StringWithAggregatesFilter<"AppCustomer"> | string
  variantId?: Prisma.StringWithAggregatesFilter<"AppCustomer"> | string
  email?: Prisma.StringWithAggregatesFilter<"AppCustomer"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"AppCustomer"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AppCustomer"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AppCustomer"> | Date | string
}

export type AppCustomerCreateInput = {
  id?: string
  appId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  variant: Prisma.AppVariantCreateNestedOneWithoutCustomersInput
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerCreateNestedOneWithoutCustomerInput
  sessions?: Prisma.CustomerSessionCreateNestedManyWithoutCustomerInput
}

export type AppCustomerUncheckedCreateInput = {
  id?: string
  appId: string
  variantId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUncheckedCreateNestedOneWithoutCustomerInput
  sessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutCustomerInput
}

export type AppCustomerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variant?: Prisma.AppVariantUpdateOneRequiredWithoutCustomersNestedInput
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUpdateOneWithoutCustomerNestedInput
  sessions?: Prisma.CustomerSessionUpdateManyWithoutCustomerNestedInput
}

export type AppCustomerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUncheckedUpdateOneWithoutCustomerNestedInput
  sessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutCustomerNestedInput
}

export type AppCustomerCreateManyInput = {
  id?: string
  appId: string
  variantId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppCustomerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppCustomerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppCustomerListRelationFilter = {
  every?: Prisma.AppCustomerWhereInput
  some?: Prisma.AppCustomerWhereInput
  none?: Prisma.AppCustomerWhereInput
}

export type AppCustomerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AppCustomerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppCustomerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppCustomerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppCustomerScalarRelationFilter = {
  is?: Prisma.AppCustomerWhereInput
  isNot?: Prisma.AppCustomerWhereInput
}

export type AppCustomerCreateNestedManyWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutVariantInput, Prisma.AppCustomerUncheckedCreateWithoutVariantInput> | Prisma.AppCustomerCreateWithoutVariantInput[] | Prisma.AppCustomerUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutVariantInput | Prisma.AppCustomerCreateOrConnectWithoutVariantInput[]
  createMany?: Prisma.AppCustomerCreateManyVariantInputEnvelope
  connect?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
}

export type AppCustomerUncheckedCreateNestedManyWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutVariantInput, Prisma.AppCustomerUncheckedCreateWithoutVariantInput> | Prisma.AppCustomerCreateWithoutVariantInput[] | Prisma.AppCustomerUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutVariantInput | Prisma.AppCustomerCreateOrConnectWithoutVariantInput[]
  createMany?: Prisma.AppCustomerCreateManyVariantInputEnvelope
  connect?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
}

export type AppCustomerUpdateManyWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutVariantInput, Prisma.AppCustomerUncheckedCreateWithoutVariantInput> | Prisma.AppCustomerCreateWithoutVariantInput[] | Prisma.AppCustomerUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutVariantInput | Prisma.AppCustomerCreateOrConnectWithoutVariantInput[]
  upsert?: Prisma.AppCustomerUpsertWithWhereUniqueWithoutVariantInput | Prisma.AppCustomerUpsertWithWhereUniqueWithoutVariantInput[]
  createMany?: Prisma.AppCustomerCreateManyVariantInputEnvelope
  set?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  disconnect?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  delete?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  connect?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  update?: Prisma.AppCustomerUpdateWithWhereUniqueWithoutVariantInput | Prisma.AppCustomerUpdateWithWhereUniqueWithoutVariantInput[]
  updateMany?: Prisma.AppCustomerUpdateManyWithWhereWithoutVariantInput | Prisma.AppCustomerUpdateManyWithWhereWithoutVariantInput[]
  deleteMany?: Prisma.AppCustomerScalarWhereInput | Prisma.AppCustomerScalarWhereInput[]
}

export type AppCustomerUncheckedUpdateManyWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutVariantInput, Prisma.AppCustomerUncheckedCreateWithoutVariantInput> | Prisma.AppCustomerCreateWithoutVariantInput[] | Prisma.AppCustomerUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutVariantInput | Prisma.AppCustomerCreateOrConnectWithoutVariantInput[]
  upsert?: Prisma.AppCustomerUpsertWithWhereUniqueWithoutVariantInput | Prisma.AppCustomerUpsertWithWhereUniqueWithoutVariantInput[]
  createMany?: Prisma.AppCustomerCreateManyVariantInputEnvelope
  set?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  disconnect?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  delete?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  connect?: Prisma.AppCustomerWhereUniqueInput | Prisma.AppCustomerWhereUniqueInput[]
  update?: Prisma.AppCustomerUpdateWithWhereUniqueWithoutVariantInput | Prisma.AppCustomerUpdateWithWhereUniqueWithoutVariantInput[]
  updateMany?: Prisma.AppCustomerUpdateManyWithWhereWithoutVariantInput | Prisma.AppCustomerUpdateManyWithWhereWithoutVariantInput[]
  deleteMany?: Prisma.AppCustomerScalarWhereInput | Prisma.AppCustomerScalarWhereInput[]
}

export type AppCustomerCreateNestedOneWithoutLemonSqueezyCustomerInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutLemonSqueezyCustomerInput, Prisma.AppCustomerUncheckedCreateWithoutLemonSqueezyCustomerInput>
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutLemonSqueezyCustomerInput
  connect?: Prisma.AppCustomerWhereUniqueInput
}

export type AppCustomerUpdateOneRequiredWithoutLemonSqueezyCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutLemonSqueezyCustomerInput, Prisma.AppCustomerUncheckedCreateWithoutLemonSqueezyCustomerInput>
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutLemonSqueezyCustomerInput
  upsert?: Prisma.AppCustomerUpsertWithoutLemonSqueezyCustomerInput
  connect?: Prisma.AppCustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppCustomerUpdateToOneWithWhereWithoutLemonSqueezyCustomerInput, Prisma.AppCustomerUpdateWithoutLemonSqueezyCustomerInput>, Prisma.AppCustomerUncheckedUpdateWithoutLemonSqueezyCustomerInput>
}

export type AppCustomerCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutSessionsInput, Prisma.AppCustomerUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutSessionsInput
  connect?: Prisma.AppCustomerWhereUniqueInput
}

export type AppCustomerUpdateOneRequiredWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.AppCustomerCreateWithoutSessionsInput, Prisma.AppCustomerUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.AppCustomerCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.AppCustomerUpsertWithoutSessionsInput
  connect?: Prisma.AppCustomerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppCustomerUpdateToOneWithWhereWithoutSessionsInput, Prisma.AppCustomerUpdateWithoutSessionsInput>, Prisma.AppCustomerUncheckedUpdateWithoutSessionsInput>
}

export type AppCustomerCreateWithoutVariantInput = {
  id?: string
  appId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerCreateNestedOneWithoutCustomerInput
  sessions?: Prisma.CustomerSessionCreateNestedManyWithoutCustomerInput
}

export type AppCustomerUncheckedCreateWithoutVariantInput = {
  id?: string
  appId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUncheckedCreateNestedOneWithoutCustomerInput
  sessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutCustomerInput
}

export type AppCustomerCreateOrConnectWithoutVariantInput = {
  where: Prisma.AppCustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCustomerCreateWithoutVariantInput, Prisma.AppCustomerUncheckedCreateWithoutVariantInput>
}

export type AppCustomerCreateManyVariantInputEnvelope = {
  data: Prisma.AppCustomerCreateManyVariantInput | Prisma.AppCustomerCreateManyVariantInput[]
  skipDuplicates?: boolean
}

export type AppCustomerUpsertWithWhereUniqueWithoutVariantInput = {
  where: Prisma.AppCustomerWhereUniqueInput
  update: Prisma.XOR<Prisma.AppCustomerUpdateWithoutVariantInput, Prisma.AppCustomerUncheckedUpdateWithoutVariantInput>
  create: Prisma.XOR<Prisma.AppCustomerCreateWithoutVariantInput, Prisma.AppCustomerUncheckedCreateWithoutVariantInput>
}

export type AppCustomerUpdateWithWhereUniqueWithoutVariantInput = {
  where: Prisma.AppCustomerWhereUniqueInput
  data: Prisma.XOR<Prisma.AppCustomerUpdateWithoutVariantInput, Prisma.AppCustomerUncheckedUpdateWithoutVariantInput>
}

export type AppCustomerUpdateManyWithWhereWithoutVariantInput = {
  where: Prisma.AppCustomerScalarWhereInput
  data: Prisma.XOR<Prisma.AppCustomerUpdateManyMutationInput, Prisma.AppCustomerUncheckedUpdateManyWithoutVariantInput>
}

export type AppCustomerScalarWhereInput = {
  AND?: Prisma.AppCustomerScalarWhereInput | Prisma.AppCustomerScalarWhereInput[]
  OR?: Prisma.AppCustomerScalarWhereInput[]
  NOT?: Prisma.AppCustomerScalarWhereInput | Prisma.AppCustomerScalarWhereInput[]
  id?: Prisma.StringFilter<"AppCustomer"> | string
  appId?: Prisma.StringFilter<"AppCustomer"> | string
  variantId?: Prisma.StringFilter<"AppCustomer"> | string
  email?: Prisma.StringFilter<"AppCustomer"> | string
  name?: Prisma.StringNullableFilter<"AppCustomer"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AppCustomer"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AppCustomer"> | Date | string
}

export type AppCustomerCreateWithoutLemonSqueezyCustomerInput = {
  id?: string
  appId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  variant: Prisma.AppVariantCreateNestedOneWithoutCustomersInput
  sessions?: Prisma.CustomerSessionCreateNestedManyWithoutCustomerInput
}

export type AppCustomerUncheckedCreateWithoutLemonSqueezyCustomerInput = {
  id?: string
  appId: string
  variantId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sessions?: Prisma.CustomerSessionUncheckedCreateNestedManyWithoutCustomerInput
}

export type AppCustomerCreateOrConnectWithoutLemonSqueezyCustomerInput = {
  where: Prisma.AppCustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCustomerCreateWithoutLemonSqueezyCustomerInput, Prisma.AppCustomerUncheckedCreateWithoutLemonSqueezyCustomerInput>
}

export type AppCustomerUpsertWithoutLemonSqueezyCustomerInput = {
  update: Prisma.XOR<Prisma.AppCustomerUpdateWithoutLemonSqueezyCustomerInput, Prisma.AppCustomerUncheckedUpdateWithoutLemonSqueezyCustomerInput>
  create: Prisma.XOR<Prisma.AppCustomerCreateWithoutLemonSqueezyCustomerInput, Prisma.AppCustomerUncheckedCreateWithoutLemonSqueezyCustomerInput>
  where?: Prisma.AppCustomerWhereInput
}

export type AppCustomerUpdateToOneWithWhereWithoutLemonSqueezyCustomerInput = {
  where?: Prisma.AppCustomerWhereInput
  data: Prisma.XOR<Prisma.AppCustomerUpdateWithoutLemonSqueezyCustomerInput, Prisma.AppCustomerUncheckedUpdateWithoutLemonSqueezyCustomerInput>
}

export type AppCustomerUpdateWithoutLemonSqueezyCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variant?: Prisma.AppVariantUpdateOneRequiredWithoutCustomersNestedInput
  sessions?: Prisma.CustomerSessionUpdateManyWithoutCustomerNestedInput
}

export type AppCustomerUncheckedUpdateWithoutLemonSqueezyCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutCustomerNestedInput
}

export type AppCustomerCreateWithoutSessionsInput = {
  id?: string
  appId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  variant: Prisma.AppVariantCreateNestedOneWithoutCustomersInput
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerCreateNestedOneWithoutCustomerInput
}

export type AppCustomerUncheckedCreateWithoutSessionsInput = {
  id?: string
  appId: string
  variantId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUncheckedCreateNestedOneWithoutCustomerInput
}

export type AppCustomerCreateOrConnectWithoutSessionsInput = {
  where: Prisma.AppCustomerWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCustomerCreateWithoutSessionsInput, Prisma.AppCustomerUncheckedCreateWithoutSessionsInput>
}

export type AppCustomerUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.AppCustomerUpdateWithoutSessionsInput, Prisma.AppCustomerUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.AppCustomerCreateWithoutSessionsInput, Prisma.AppCustomerUncheckedCreateWithoutSessionsInput>
  where?: Prisma.AppCustomerWhereInput
}

export type AppCustomerUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.AppCustomerWhereInput
  data: Prisma.XOR<Prisma.AppCustomerUpdateWithoutSessionsInput, Prisma.AppCustomerUncheckedUpdateWithoutSessionsInput>
}

export type AppCustomerUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variant?: Prisma.AppVariantUpdateOneRequiredWithoutCustomersNestedInput
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUpdateOneWithoutCustomerNestedInput
}

export type AppCustomerUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUncheckedUpdateOneWithoutCustomerNestedInput
}

export type AppCustomerCreateManyVariantInput = {
  id?: string
  appId: string
  email: string
  name?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppCustomerUpdateWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUpdateOneWithoutCustomerNestedInput
  sessions?: Prisma.CustomerSessionUpdateManyWithoutCustomerNestedInput
}

export type AppCustomerUncheckedUpdateWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lemonSqueezyCustomer?: Prisma.LemonSqueezyCustomerUncheckedUpdateOneWithoutCustomerNestedInput
  sessions?: Prisma.CustomerSessionUncheckedUpdateManyWithoutCustomerNestedInput
}

export type AppCustomerUncheckedUpdateManyWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AppCustomerCountOutputType
 */

export type AppCustomerCountOutputType = {
  sessions: number
}

export type AppCustomerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | AppCustomerCountOutputTypeCountSessionsArgs
}

/**
 * AppCustomerCountOutputType without action
 */
export type AppCustomerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomerCountOutputType
   */
  select?: Prisma.AppCustomerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AppCustomerCountOutputType without action
 */
export type AppCustomerCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomerSessionWhereInput
}


export type AppCustomerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appId?: boolean
  variantId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.AppVariantDefaultArgs<ExtArgs>
  lemonSqueezyCustomer?: boolean | Prisma.AppCustomer$lemonSqueezyCustomerArgs<ExtArgs>
  sessions?: boolean | Prisma.AppCustomer$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.AppCustomerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appCustomer"]>

export type AppCustomerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appId?: boolean
  variantId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.AppVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appCustomer"]>

export type AppCustomerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appId?: boolean
  variantId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.AppVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appCustomer"]>

export type AppCustomerSelectScalar = {
  id?: boolean
  appId?: boolean
  variantId?: boolean
  email?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AppCustomerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "appId" | "variantId" | "email" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["appCustomer"]>
export type AppCustomerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.AppVariantDefaultArgs<ExtArgs>
  lemonSqueezyCustomer?: boolean | Prisma.AppCustomer$lemonSqueezyCustomerArgs<ExtArgs>
  sessions?: boolean | Prisma.AppCustomer$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.AppCustomerCountOutputTypeDefaultArgs<ExtArgs>
}
export type AppCustomerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.AppVariantDefaultArgs<ExtArgs>
}
export type AppCustomerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.AppVariantDefaultArgs<ExtArgs>
}

export type $AppCustomerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AppCustomer"
  objects: {
    variant: Prisma.$AppVariantPayload<ExtArgs>
    lemonSqueezyCustomer: Prisma.$LemonSqueezyCustomerPayload<ExtArgs> | null
    sessions: Prisma.$CustomerSessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    appId: string
    variantId: string
    email: string
    name: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["appCustomer"]>
  composites: {}
}

export type AppCustomerGetPayload<S extends boolean | null | undefined | AppCustomerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload, S>

export type AppCustomerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppCustomerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppCustomerCountAggregateInputType | true
  }

export interface AppCustomerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AppCustomer'], meta: { name: 'AppCustomer' } }
  /**
   * Find zero or one AppCustomer that matches the filter.
   * @param {AppCustomerFindUniqueArgs} args - Arguments to find a AppCustomer
   * @example
   * // Get one AppCustomer
   * const appCustomer = await prisma.appCustomer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppCustomerFindUniqueArgs>(args: Prisma.SelectSubset<T, AppCustomerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AppCustomer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppCustomerFindUniqueOrThrowArgs} args - Arguments to find a AppCustomer
   * @example
   * // Get one AppCustomer
   * const appCustomer = await prisma.appCustomer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppCustomerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppCustomerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppCustomer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCustomerFindFirstArgs} args - Arguments to find a AppCustomer
   * @example
   * // Get one AppCustomer
   * const appCustomer = await prisma.appCustomer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppCustomerFindFirstArgs>(args?: Prisma.SelectSubset<T, AppCustomerFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppCustomer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCustomerFindFirstOrThrowArgs} args - Arguments to find a AppCustomer
   * @example
   * // Get one AppCustomer
   * const appCustomer = await prisma.appCustomer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppCustomerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppCustomerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AppCustomers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCustomerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AppCustomers
   * const appCustomers = await prisma.appCustomer.findMany()
   * 
   * // Get first 10 AppCustomers
   * const appCustomers = await prisma.appCustomer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const appCustomerWithIdOnly = await prisma.appCustomer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AppCustomerFindManyArgs>(args?: Prisma.SelectSubset<T, AppCustomerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AppCustomer.
   * @param {AppCustomerCreateArgs} args - Arguments to create a AppCustomer.
   * @example
   * // Create one AppCustomer
   * const AppCustomer = await prisma.appCustomer.create({
   *   data: {
   *     // ... data to create a AppCustomer
   *   }
   * })
   * 
   */
  create<T extends AppCustomerCreateArgs>(args: Prisma.SelectSubset<T, AppCustomerCreateArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AppCustomers.
   * @param {AppCustomerCreateManyArgs} args - Arguments to create many AppCustomers.
   * @example
   * // Create many AppCustomers
   * const appCustomer = await prisma.appCustomer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppCustomerCreateManyArgs>(args?: Prisma.SelectSubset<T, AppCustomerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AppCustomers and returns the data saved in the database.
   * @param {AppCustomerCreateManyAndReturnArgs} args - Arguments to create many AppCustomers.
   * @example
   * // Create many AppCustomers
   * const appCustomer = await prisma.appCustomer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AppCustomers and only return the `id`
   * const appCustomerWithIdOnly = await prisma.appCustomer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppCustomerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppCustomerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AppCustomer.
   * @param {AppCustomerDeleteArgs} args - Arguments to delete one AppCustomer.
   * @example
   * // Delete one AppCustomer
   * const AppCustomer = await prisma.appCustomer.delete({
   *   where: {
   *     // ... filter to delete one AppCustomer
   *   }
   * })
   * 
   */
  delete<T extends AppCustomerDeleteArgs>(args: Prisma.SelectSubset<T, AppCustomerDeleteArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AppCustomer.
   * @param {AppCustomerUpdateArgs} args - Arguments to update one AppCustomer.
   * @example
   * // Update one AppCustomer
   * const appCustomer = await prisma.appCustomer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppCustomerUpdateArgs>(args: Prisma.SelectSubset<T, AppCustomerUpdateArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AppCustomers.
   * @param {AppCustomerDeleteManyArgs} args - Arguments to filter AppCustomers to delete.
   * @example
   * // Delete a few AppCustomers
   * const { count } = await prisma.appCustomer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppCustomerDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppCustomerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppCustomers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCustomerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AppCustomers
   * const appCustomer = await prisma.appCustomer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppCustomerUpdateManyArgs>(args: Prisma.SelectSubset<T, AppCustomerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppCustomers and returns the data updated in the database.
   * @param {AppCustomerUpdateManyAndReturnArgs} args - Arguments to update many AppCustomers.
   * @example
   * // Update many AppCustomers
   * const appCustomer = await prisma.appCustomer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AppCustomers and only return the `id`
   * const appCustomerWithIdOnly = await prisma.appCustomer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppCustomerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppCustomerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AppCustomer.
   * @param {AppCustomerUpsertArgs} args - Arguments to update or create a AppCustomer.
   * @example
   * // Update or create a AppCustomer
   * const appCustomer = await prisma.appCustomer.upsert({
   *   create: {
   *     // ... data to create a AppCustomer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AppCustomer we want to update
   *   }
   * })
   */
  upsert<T extends AppCustomerUpsertArgs>(args: Prisma.SelectSubset<T, AppCustomerUpsertArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AppCustomers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCustomerCountArgs} args - Arguments to filter AppCustomers to count.
   * @example
   * // Count the number of AppCustomers
   * const count = await prisma.appCustomer.count({
   *   where: {
   *     // ... the filter for the AppCustomers we want to count
   *   }
   * })
  **/
  count<T extends AppCustomerCountArgs>(
    args?: Prisma.Subset<T, AppCustomerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppCustomerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AppCustomer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCustomerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppCustomerAggregateArgs>(args: Prisma.Subset<T, AppCustomerAggregateArgs>): Prisma.PrismaPromise<GetAppCustomerAggregateType<T>>

  /**
   * Group by AppCustomer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCustomerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppCustomerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppCustomerGroupByArgs['orderBy'] }
      : { orderBy?: AppCustomerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppCustomerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppCustomerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AppCustomer model
 */
readonly fields: AppCustomerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AppCustomer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppCustomerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  variant<T extends Prisma.AppVariantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppVariantDefaultArgs<ExtArgs>>): Prisma.Prisma__AppVariantClient<runtime.Types.Result.GetResult<Prisma.$AppVariantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  lemonSqueezyCustomer<T extends Prisma.AppCustomer$lemonSqueezyCustomerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppCustomer$lemonSqueezyCustomerArgs<ExtArgs>>): Prisma.Prisma__LemonSqueezyCustomerClient<runtime.Types.Result.GetResult<Prisma.$LemonSqueezyCustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  sessions<T extends Prisma.AppCustomer$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppCustomer$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AppCustomer model
 */
export interface AppCustomerFieldRefs {
  readonly id: Prisma.FieldRef<"AppCustomer", 'String'>
  readonly appId: Prisma.FieldRef<"AppCustomer", 'String'>
  readonly variantId: Prisma.FieldRef<"AppCustomer", 'String'>
  readonly email: Prisma.FieldRef<"AppCustomer", 'String'>
  readonly name: Prisma.FieldRef<"AppCustomer", 'String'>
  readonly createdAt: Prisma.FieldRef<"AppCustomer", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AppCustomer", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AppCustomer findUnique
 */
export type AppCustomerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * Filter, which AppCustomer to fetch.
   */
  where: Prisma.AppCustomerWhereUniqueInput
}

/**
 * AppCustomer findUniqueOrThrow
 */
export type AppCustomerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * Filter, which AppCustomer to fetch.
   */
  where: Prisma.AppCustomerWhereUniqueInput
}

/**
 * AppCustomer findFirst
 */
export type AppCustomerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * Filter, which AppCustomer to fetch.
   */
  where?: Prisma.AppCustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCustomers to fetch.
   */
  orderBy?: Prisma.AppCustomerOrderByWithRelationInput | Prisma.AppCustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppCustomers.
   */
  cursor?: Prisma.AppCustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCustomers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCustomers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppCustomers.
   */
  distinct?: Prisma.AppCustomerScalarFieldEnum | Prisma.AppCustomerScalarFieldEnum[]
}

/**
 * AppCustomer findFirstOrThrow
 */
export type AppCustomerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * Filter, which AppCustomer to fetch.
   */
  where?: Prisma.AppCustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCustomers to fetch.
   */
  orderBy?: Prisma.AppCustomerOrderByWithRelationInput | Prisma.AppCustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppCustomers.
   */
  cursor?: Prisma.AppCustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCustomers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCustomers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppCustomers.
   */
  distinct?: Prisma.AppCustomerScalarFieldEnum | Prisma.AppCustomerScalarFieldEnum[]
}

/**
 * AppCustomer findMany
 */
export type AppCustomerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * Filter, which AppCustomers to fetch.
   */
  where?: Prisma.AppCustomerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCustomers to fetch.
   */
  orderBy?: Prisma.AppCustomerOrderByWithRelationInput | Prisma.AppCustomerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AppCustomers.
   */
  cursor?: Prisma.AppCustomerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCustomers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCustomers.
   */
  skip?: number
  distinct?: Prisma.AppCustomerScalarFieldEnum | Prisma.AppCustomerScalarFieldEnum[]
}

/**
 * AppCustomer create
 */
export type AppCustomerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * The data needed to create a AppCustomer.
   */
  data: Prisma.XOR<Prisma.AppCustomerCreateInput, Prisma.AppCustomerUncheckedCreateInput>
}

/**
 * AppCustomer createMany
 */
export type AppCustomerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AppCustomers.
   */
  data: Prisma.AppCustomerCreateManyInput | Prisma.AppCustomerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AppCustomer createManyAndReturn
 */
export type AppCustomerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * The data used to create many AppCustomers.
   */
  data: Prisma.AppCustomerCreateManyInput | Prisma.AppCustomerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AppCustomer update
 */
export type AppCustomerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * The data needed to update a AppCustomer.
   */
  data: Prisma.XOR<Prisma.AppCustomerUpdateInput, Prisma.AppCustomerUncheckedUpdateInput>
  /**
   * Choose, which AppCustomer to update.
   */
  where: Prisma.AppCustomerWhereUniqueInput
}

/**
 * AppCustomer updateMany
 */
export type AppCustomerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AppCustomers.
   */
  data: Prisma.XOR<Prisma.AppCustomerUpdateManyMutationInput, Prisma.AppCustomerUncheckedUpdateManyInput>
  /**
   * Filter which AppCustomers to update
   */
  where?: Prisma.AppCustomerWhereInput
  /**
   * Limit how many AppCustomers to update.
   */
  limit?: number
}

/**
 * AppCustomer updateManyAndReturn
 */
export type AppCustomerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * The data used to update AppCustomers.
   */
  data: Prisma.XOR<Prisma.AppCustomerUpdateManyMutationInput, Prisma.AppCustomerUncheckedUpdateManyInput>
  /**
   * Filter which AppCustomers to update
   */
  where?: Prisma.AppCustomerWhereInput
  /**
   * Limit how many AppCustomers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AppCustomer upsert
 */
export type AppCustomerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * The filter to search for the AppCustomer to update in case it exists.
   */
  where: Prisma.AppCustomerWhereUniqueInput
  /**
   * In case the AppCustomer found by the `where` argument doesn't exist, create a new AppCustomer with this data.
   */
  create: Prisma.XOR<Prisma.AppCustomerCreateInput, Prisma.AppCustomerUncheckedCreateInput>
  /**
   * In case the AppCustomer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppCustomerUpdateInput, Prisma.AppCustomerUncheckedUpdateInput>
}

/**
 * AppCustomer delete
 */
export type AppCustomerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
  /**
   * Filter which AppCustomer to delete.
   */
  where: Prisma.AppCustomerWhereUniqueInput
}

/**
 * AppCustomer deleteMany
 */
export type AppCustomerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppCustomers to delete
   */
  where?: Prisma.AppCustomerWhereInput
  /**
   * Limit how many AppCustomers to delete.
   */
  limit?: number
}

/**
 * AppCustomer.lemonSqueezyCustomer
 */
export type AppCustomer$lemonSqueezyCustomerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LemonSqueezyCustomer
   */
  select?: Prisma.LemonSqueezyCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LemonSqueezyCustomer
   */
  omit?: Prisma.LemonSqueezyCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LemonSqueezyCustomerInclude<ExtArgs> | null
  where?: Prisma.LemonSqueezyCustomerWhereInput
}

/**
 * AppCustomer.sessions
 */
export type AppCustomer$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerSession
   */
  select?: Prisma.CustomerSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerSession
   */
  omit?: Prisma.CustomerSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerSessionInclude<ExtArgs> | null
  where?: Prisma.CustomerSessionWhereInput
  orderBy?: Prisma.CustomerSessionOrderByWithRelationInput | Prisma.CustomerSessionOrderByWithRelationInput[]
  cursor?: Prisma.CustomerSessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CustomerSessionScalarFieldEnum | Prisma.CustomerSessionScalarFieldEnum[]
}

/**
 * AppCustomer without action
 */
export type AppCustomerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCustomer
   */
  select?: Prisma.AppCustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCustomer
   */
  omit?: Prisma.AppCustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCustomerInclude<ExtArgs> | null
}
