
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `AppCourseProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AppCourseProfile
 * 
 */
export type AppCourseProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$AppCourseProfilePayload>

export type AggregateAppCourseProfile = {
  _count: AppCourseProfileCountAggregateOutputType | null
  _min: AppCourseProfileMinAggregateOutputType | null
  _max: AppCourseProfileMaxAggregateOutputType | null
}

export type AppCourseProfileMinAggregateOutputType = {
  appId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppCourseProfileMaxAggregateOutputType = {
  appId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppCourseProfileCountAggregateOutputType = {
  appId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AppCourseProfileMinAggregateInputType = {
  appId?: true
  createdAt?: true
  updatedAt?: true
}

export type AppCourseProfileMaxAggregateInputType = {
  appId?: true
  createdAt?: true
  updatedAt?: true
}

export type AppCourseProfileCountAggregateInputType = {
  appId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AppCourseProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppCourseProfile to aggregate.
   */
  where?: Prisma.AppCourseProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCourseProfiles to fetch.
   */
  orderBy?: Prisma.AppCourseProfileOrderByWithRelationInput | Prisma.AppCourseProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppCourseProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCourseProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCourseProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AppCourseProfiles
  **/
  _count?: true | AppCourseProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppCourseProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppCourseProfileMaxAggregateInputType
}

export type GetAppCourseProfileAggregateType<T extends AppCourseProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateAppCourseProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppCourseProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateAppCourseProfile[P]>
}




export type AppCourseProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppCourseProfileWhereInput
  orderBy?: Prisma.AppCourseProfileOrderByWithAggregationInput | Prisma.AppCourseProfileOrderByWithAggregationInput[]
  by: Prisma.AppCourseProfileScalarFieldEnum[] | Prisma.AppCourseProfileScalarFieldEnum
  having?: Prisma.AppCourseProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppCourseProfileCountAggregateInputType | true
  _min?: AppCourseProfileMinAggregateInputType
  _max?: AppCourseProfileMaxAggregateInputType
}

export type AppCourseProfileGroupByOutputType = {
  appId: string
  createdAt: Date
  updatedAt: Date
  _count: AppCourseProfileCountAggregateOutputType | null
  _min: AppCourseProfileMinAggregateOutputType | null
  _max: AppCourseProfileMaxAggregateOutputType | null
}

type GetAppCourseProfileGroupByPayload<T extends AppCourseProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppCourseProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppCourseProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppCourseProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppCourseProfileGroupByOutputType[P]>
      }
    >
  > 



export type AppCourseProfileWhereInput = {
  AND?: Prisma.AppCourseProfileWhereInput | Prisma.AppCourseProfileWhereInput[]
  OR?: Prisma.AppCourseProfileWhereInput[]
  NOT?: Prisma.AppCourseProfileWhereInput | Prisma.AppCourseProfileWhereInput[]
  appId?: Prisma.StringFilter<"AppCourseProfile"> | string
  createdAt?: Prisma.DateTimeFilter<"AppCourseProfile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AppCourseProfile"> | Date | string
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
  modules?: Prisma.CourseModuleListRelationFilter
  appFront?: Prisma.XOR<Prisma.AppFrontNullableScalarRelationFilter, Prisma.AppFrontWhereInput> | null
}

export type AppCourseProfileOrderByWithRelationInput = {
  appId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  app?: Prisma.AppOrderByWithRelationInput
  modules?: Prisma.CourseModuleOrderByRelationAggregateInput
  appFront?: Prisma.AppFrontOrderByWithRelationInput
}

export type AppCourseProfileWhereUniqueInput = Prisma.AtLeast<{
  appId?: string
  AND?: Prisma.AppCourseProfileWhereInput | Prisma.AppCourseProfileWhereInput[]
  OR?: Prisma.AppCourseProfileWhereInput[]
  NOT?: Prisma.AppCourseProfileWhereInput | Prisma.AppCourseProfileWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"AppCourseProfile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AppCourseProfile"> | Date | string
  app?: Prisma.XOR<Prisma.AppScalarRelationFilter, Prisma.AppWhereInput>
  modules?: Prisma.CourseModuleListRelationFilter
  appFront?: Prisma.XOR<Prisma.AppFrontNullableScalarRelationFilter, Prisma.AppFrontWhereInput> | null
}, "appId">

export type AppCourseProfileOrderByWithAggregationInput = {
  appId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AppCourseProfileCountOrderByAggregateInput
  _max?: Prisma.AppCourseProfileMaxOrderByAggregateInput
  _min?: Prisma.AppCourseProfileMinOrderByAggregateInput
}

export type AppCourseProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppCourseProfileScalarWhereWithAggregatesInput | Prisma.AppCourseProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppCourseProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppCourseProfileScalarWhereWithAggregatesInput | Prisma.AppCourseProfileScalarWhereWithAggregatesInput[]
  appId?: Prisma.StringWithAggregatesFilter<"AppCourseProfile"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AppCourseProfile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AppCourseProfile"> | Date | string
}

export type AppCourseProfileCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  app: Prisma.AppCreateNestedOneWithoutCourseProfileInput
  modules?: Prisma.CourseModuleCreateNestedManyWithoutCourseInput
  appFront?: Prisma.AppFrontCreateNestedOneWithoutAppCourseProfileInput
}

export type AppCourseProfileUncheckedCreateInput = {
  appId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  modules?: Prisma.CourseModuleUncheckedCreateNestedManyWithoutCourseInput
  appFront?: Prisma.AppFrontUncheckedCreateNestedOneWithoutAppCourseProfileInput
}

export type AppCourseProfileUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  app?: Prisma.AppUpdateOneRequiredWithoutCourseProfileNestedInput
  modules?: Prisma.CourseModuleUpdateManyWithoutCourseNestedInput
  appFront?: Prisma.AppFrontUpdateOneWithoutAppCourseProfileNestedInput
}

export type AppCourseProfileUncheckedUpdateInput = {
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modules?: Prisma.CourseModuleUncheckedUpdateManyWithoutCourseNestedInput
  appFront?: Prisma.AppFrontUncheckedUpdateOneWithoutAppCourseProfileNestedInput
}

export type AppCourseProfileCreateManyInput = {
  appId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppCourseProfileUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppCourseProfileUncheckedUpdateManyInput = {
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppCourseProfileNullableScalarRelationFilter = {
  is?: Prisma.AppCourseProfileWhereInput | null
  isNot?: Prisma.AppCourseProfileWhereInput | null
}

export type AppCourseProfileCountOrderByAggregateInput = {
  appId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppCourseProfileMaxOrderByAggregateInput = {
  appId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppCourseProfileMinOrderByAggregateInput = {
  appId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppCourseProfileScalarRelationFilter = {
  is?: Prisma.AppCourseProfileWhereInput
  isNot?: Prisma.AppCourseProfileWhereInput
}

export type AppCourseProfileCreateNestedOneWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutAppInput
  connect?: Prisma.AppCourseProfileWhereUniqueInput
}

export type AppCourseProfileUncheckedCreateNestedOneWithoutAppInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutAppInput
  connect?: Prisma.AppCourseProfileWhereUniqueInput
}

export type AppCourseProfileUpdateOneWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutAppInput
  upsert?: Prisma.AppCourseProfileUpsertWithoutAppInput
  disconnect?: Prisma.AppCourseProfileWhereInput | boolean
  delete?: Prisma.AppCourseProfileWhereInput | boolean
  connect?: Prisma.AppCourseProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppCourseProfileUpdateToOneWithWhereWithoutAppInput, Prisma.AppCourseProfileUpdateWithoutAppInput>, Prisma.AppCourseProfileUncheckedUpdateWithoutAppInput>
}

export type AppCourseProfileUncheckedUpdateOneWithoutAppNestedInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutAppInput
  upsert?: Prisma.AppCourseProfileUpsertWithoutAppInput
  disconnect?: Prisma.AppCourseProfileWhereInput | boolean
  delete?: Prisma.AppCourseProfileWhereInput | boolean
  connect?: Prisma.AppCourseProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppCourseProfileUpdateToOneWithWhereWithoutAppInput, Prisma.AppCourseProfileUpdateWithoutAppInput>, Prisma.AppCourseProfileUncheckedUpdateWithoutAppInput>
}

export type AppCourseProfileCreateNestedOneWithoutModulesInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutModulesInput, Prisma.AppCourseProfileUncheckedCreateWithoutModulesInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutModulesInput
  connect?: Prisma.AppCourseProfileWhereUniqueInput
}

export type AppCourseProfileUpdateOneRequiredWithoutModulesNestedInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutModulesInput, Prisma.AppCourseProfileUncheckedCreateWithoutModulesInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutModulesInput
  upsert?: Prisma.AppCourseProfileUpsertWithoutModulesInput
  connect?: Prisma.AppCourseProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppCourseProfileUpdateToOneWithWhereWithoutModulesInput, Prisma.AppCourseProfileUpdateWithoutModulesInput>, Prisma.AppCourseProfileUncheckedUpdateWithoutModulesInput>
}

export type AppCourseProfileCreateNestedOneWithoutAppFrontInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppFrontInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppFrontInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutAppFrontInput
  connect?: Prisma.AppCourseProfileWhereUniqueInput
}

export type AppCourseProfileUpdateOneRequiredWithoutAppFrontNestedInput = {
  create?: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppFrontInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppFrontInput>
  connectOrCreate?: Prisma.AppCourseProfileCreateOrConnectWithoutAppFrontInput
  upsert?: Prisma.AppCourseProfileUpsertWithoutAppFrontInput
  connect?: Prisma.AppCourseProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppCourseProfileUpdateToOneWithWhereWithoutAppFrontInput, Prisma.AppCourseProfileUpdateWithoutAppFrontInput>, Prisma.AppCourseProfileUncheckedUpdateWithoutAppFrontInput>
}

export type AppCourseProfileCreateWithoutAppInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  modules?: Prisma.CourseModuleCreateNestedManyWithoutCourseInput
  appFront?: Prisma.AppFrontCreateNestedOneWithoutAppCourseProfileInput
}

export type AppCourseProfileUncheckedCreateWithoutAppInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  modules?: Prisma.CourseModuleUncheckedCreateNestedManyWithoutCourseInput
  appFront?: Prisma.AppFrontUncheckedCreateNestedOneWithoutAppCourseProfileInput
}

export type AppCourseProfileCreateOrConnectWithoutAppInput = {
  where: Prisma.AppCourseProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppInput>
}

export type AppCourseProfileUpsertWithoutAppInput = {
  update: Prisma.XOR<Prisma.AppCourseProfileUpdateWithoutAppInput, Prisma.AppCourseProfileUncheckedUpdateWithoutAppInput>
  create: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppInput>
  where?: Prisma.AppCourseProfileWhereInput
}

export type AppCourseProfileUpdateToOneWithWhereWithoutAppInput = {
  where?: Prisma.AppCourseProfileWhereInput
  data: Prisma.XOR<Prisma.AppCourseProfileUpdateWithoutAppInput, Prisma.AppCourseProfileUncheckedUpdateWithoutAppInput>
}

export type AppCourseProfileUpdateWithoutAppInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modules?: Prisma.CourseModuleUpdateManyWithoutCourseNestedInput
  appFront?: Prisma.AppFrontUpdateOneWithoutAppCourseProfileNestedInput
}

export type AppCourseProfileUncheckedUpdateWithoutAppInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modules?: Prisma.CourseModuleUncheckedUpdateManyWithoutCourseNestedInput
  appFront?: Prisma.AppFrontUncheckedUpdateOneWithoutAppCourseProfileNestedInput
}

export type AppCourseProfileCreateWithoutModulesInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  app: Prisma.AppCreateNestedOneWithoutCourseProfileInput
  appFront?: Prisma.AppFrontCreateNestedOneWithoutAppCourseProfileInput
}

export type AppCourseProfileUncheckedCreateWithoutModulesInput = {
  appId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  appFront?: Prisma.AppFrontUncheckedCreateNestedOneWithoutAppCourseProfileInput
}

export type AppCourseProfileCreateOrConnectWithoutModulesInput = {
  where: Prisma.AppCourseProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutModulesInput, Prisma.AppCourseProfileUncheckedCreateWithoutModulesInput>
}

export type AppCourseProfileUpsertWithoutModulesInput = {
  update: Prisma.XOR<Prisma.AppCourseProfileUpdateWithoutModulesInput, Prisma.AppCourseProfileUncheckedUpdateWithoutModulesInput>
  create: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutModulesInput, Prisma.AppCourseProfileUncheckedCreateWithoutModulesInput>
  where?: Prisma.AppCourseProfileWhereInput
}

export type AppCourseProfileUpdateToOneWithWhereWithoutModulesInput = {
  where?: Prisma.AppCourseProfileWhereInput
  data: Prisma.XOR<Prisma.AppCourseProfileUpdateWithoutModulesInput, Prisma.AppCourseProfileUncheckedUpdateWithoutModulesInput>
}

export type AppCourseProfileUpdateWithoutModulesInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  app?: Prisma.AppUpdateOneRequiredWithoutCourseProfileNestedInput
  appFront?: Prisma.AppFrontUpdateOneWithoutAppCourseProfileNestedInput
}

export type AppCourseProfileUncheckedUpdateWithoutModulesInput = {
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appFront?: Prisma.AppFrontUncheckedUpdateOneWithoutAppCourseProfileNestedInput
}

export type AppCourseProfileCreateWithoutAppFrontInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  app: Prisma.AppCreateNestedOneWithoutCourseProfileInput
  modules?: Prisma.CourseModuleCreateNestedManyWithoutCourseInput
}

export type AppCourseProfileUncheckedCreateWithoutAppFrontInput = {
  appId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  modules?: Prisma.CourseModuleUncheckedCreateNestedManyWithoutCourseInput
}

export type AppCourseProfileCreateOrConnectWithoutAppFrontInput = {
  where: Prisma.AppCourseProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppFrontInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppFrontInput>
}

export type AppCourseProfileUpsertWithoutAppFrontInput = {
  update: Prisma.XOR<Prisma.AppCourseProfileUpdateWithoutAppFrontInput, Prisma.AppCourseProfileUncheckedUpdateWithoutAppFrontInput>
  create: Prisma.XOR<Prisma.AppCourseProfileCreateWithoutAppFrontInput, Prisma.AppCourseProfileUncheckedCreateWithoutAppFrontInput>
  where?: Prisma.AppCourseProfileWhereInput
}

export type AppCourseProfileUpdateToOneWithWhereWithoutAppFrontInput = {
  where?: Prisma.AppCourseProfileWhereInput
  data: Prisma.XOR<Prisma.AppCourseProfileUpdateWithoutAppFrontInput, Prisma.AppCourseProfileUncheckedUpdateWithoutAppFrontInput>
}

export type AppCourseProfileUpdateWithoutAppFrontInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  app?: Prisma.AppUpdateOneRequiredWithoutCourseProfileNestedInput
  modules?: Prisma.CourseModuleUpdateManyWithoutCourseNestedInput
}

export type AppCourseProfileUncheckedUpdateWithoutAppFrontInput = {
  appId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  modules?: Prisma.CourseModuleUncheckedUpdateManyWithoutCourseNestedInput
}


/**
 * Count Type AppCourseProfileCountOutputType
 */

export type AppCourseProfileCountOutputType = {
  modules: number
}

export type AppCourseProfileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  modules?: boolean | AppCourseProfileCountOutputTypeCountModulesArgs
}

/**
 * AppCourseProfileCountOutputType without action
 */
export type AppCourseProfileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfileCountOutputType
   */
  select?: Prisma.AppCourseProfileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AppCourseProfileCountOutputType without action
 */
export type AppCourseProfileCountOutputTypeCountModulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CourseModuleWhereInput
}


export type AppCourseProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  appId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  modules?: boolean | Prisma.AppCourseProfile$modulesArgs<ExtArgs>
  appFront?: boolean | Prisma.AppCourseProfile$appFrontArgs<ExtArgs>
  _count?: boolean | Prisma.AppCourseProfileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appCourseProfile"]>

export type AppCourseProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  appId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appCourseProfile"]>

export type AppCourseProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  appId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appCourseProfile"]>

export type AppCourseProfileSelectScalar = {
  appId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AppCourseProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"appId" | "createdAt" | "updatedAt", ExtArgs["result"]["appCourseProfile"]>
export type AppCourseProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
  modules?: boolean | Prisma.AppCourseProfile$modulesArgs<ExtArgs>
  appFront?: boolean | Prisma.AppCourseProfile$appFrontArgs<ExtArgs>
  _count?: boolean | Prisma.AppCourseProfileCountOutputTypeDefaultArgs<ExtArgs>
}
export type AppCourseProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}
export type AppCourseProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  app?: boolean | Prisma.AppDefaultArgs<ExtArgs>
}

export type $AppCourseProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AppCourseProfile"
  objects: {
    app: Prisma.$AppPayload<ExtArgs>
    modules: Prisma.$CourseModulePayload<ExtArgs>[]
    appFront: Prisma.$AppFrontPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    appId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["appCourseProfile"]>
  composites: {}
}

export type AppCourseProfileGetPayload<S extends boolean | null | undefined | AppCourseProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload, S>

export type AppCourseProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppCourseProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppCourseProfileCountAggregateInputType | true
  }

export interface AppCourseProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AppCourseProfile'], meta: { name: 'AppCourseProfile' } }
  /**
   * Find zero or one AppCourseProfile that matches the filter.
   * @param {AppCourseProfileFindUniqueArgs} args - Arguments to find a AppCourseProfile
   * @example
   * // Get one AppCourseProfile
   * const appCourseProfile = await prisma.appCourseProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppCourseProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, AppCourseProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AppCourseProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppCourseProfileFindUniqueOrThrowArgs} args - Arguments to find a AppCourseProfile
   * @example
   * // Get one AppCourseProfile
   * const appCourseProfile = await prisma.appCourseProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppCourseProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppCourseProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppCourseProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCourseProfileFindFirstArgs} args - Arguments to find a AppCourseProfile
   * @example
   * // Get one AppCourseProfile
   * const appCourseProfile = await prisma.appCourseProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppCourseProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, AppCourseProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppCourseProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCourseProfileFindFirstOrThrowArgs} args - Arguments to find a AppCourseProfile
   * @example
   * // Get one AppCourseProfile
   * const appCourseProfile = await prisma.appCourseProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppCourseProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppCourseProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AppCourseProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCourseProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AppCourseProfiles
   * const appCourseProfiles = await prisma.appCourseProfile.findMany()
   * 
   * // Get first 10 AppCourseProfiles
   * const appCourseProfiles = await prisma.appCourseProfile.findMany({ take: 10 })
   * 
   * // Only select the `appId`
   * const appCourseProfileWithAppIdOnly = await prisma.appCourseProfile.findMany({ select: { appId: true } })
   * 
   */
  findMany<T extends AppCourseProfileFindManyArgs>(args?: Prisma.SelectSubset<T, AppCourseProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AppCourseProfile.
   * @param {AppCourseProfileCreateArgs} args - Arguments to create a AppCourseProfile.
   * @example
   * // Create one AppCourseProfile
   * const AppCourseProfile = await prisma.appCourseProfile.create({
   *   data: {
   *     // ... data to create a AppCourseProfile
   *   }
   * })
   * 
   */
  create<T extends AppCourseProfileCreateArgs>(args: Prisma.SelectSubset<T, AppCourseProfileCreateArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AppCourseProfiles.
   * @param {AppCourseProfileCreateManyArgs} args - Arguments to create many AppCourseProfiles.
   * @example
   * // Create many AppCourseProfiles
   * const appCourseProfile = await prisma.appCourseProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppCourseProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, AppCourseProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AppCourseProfiles and returns the data saved in the database.
   * @param {AppCourseProfileCreateManyAndReturnArgs} args - Arguments to create many AppCourseProfiles.
   * @example
   * // Create many AppCourseProfiles
   * const appCourseProfile = await prisma.appCourseProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AppCourseProfiles and only return the `appId`
   * const appCourseProfileWithAppIdOnly = await prisma.appCourseProfile.createManyAndReturn({
   *   select: { appId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppCourseProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppCourseProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AppCourseProfile.
   * @param {AppCourseProfileDeleteArgs} args - Arguments to delete one AppCourseProfile.
   * @example
   * // Delete one AppCourseProfile
   * const AppCourseProfile = await prisma.appCourseProfile.delete({
   *   where: {
   *     // ... filter to delete one AppCourseProfile
   *   }
   * })
   * 
   */
  delete<T extends AppCourseProfileDeleteArgs>(args: Prisma.SelectSubset<T, AppCourseProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AppCourseProfile.
   * @param {AppCourseProfileUpdateArgs} args - Arguments to update one AppCourseProfile.
   * @example
   * // Update one AppCourseProfile
   * const appCourseProfile = await prisma.appCourseProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppCourseProfileUpdateArgs>(args: Prisma.SelectSubset<T, AppCourseProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AppCourseProfiles.
   * @param {AppCourseProfileDeleteManyArgs} args - Arguments to filter AppCourseProfiles to delete.
   * @example
   * // Delete a few AppCourseProfiles
   * const { count } = await prisma.appCourseProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppCourseProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppCourseProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppCourseProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCourseProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AppCourseProfiles
   * const appCourseProfile = await prisma.appCourseProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppCourseProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, AppCourseProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppCourseProfiles and returns the data updated in the database.
   * @param {AppCourseProfileUpdateManyAndReturnArgs} args - Arguments to update many AppCourseProfiles.
   * @example
   * // Update many AppCourseProfiles
   * const appCourseProfile = await prisma.appCourseProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AppCourseProfiles and only return the `appId`
   * const appCourseProfileWithAppIdOnly = await prisma.appCourseProfile.updateManyAndReturn({
   *   select: { appId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppCourseProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppCourseProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AppCourseProfile.
   * @param {AppCourseProfileUpsertArgs} args - Arguments to update or create a AppCourseProfile.
   * @example
   * // Update or create a AppCourseProfile
   * const appCourseProfile = await prisma.appCourseProfile.upsert({
   *   create: {
   *     // ... data to create a AppCourseProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AppCourseProfile we want to update
   *   }
   * })
   */
  upsert<T extends AppCourseProfileUpsertArgs>(args: Prisma.SelectSubset<T, AppCourseProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__AppCourseProfileClient<runtime.Types.Result.GetResult<Prisma.$AppCourseProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AppCourseProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCourseProfileCountArgs} args - Arguments to filter AppCourseProfiles to count.
   * @example
   * // Count the number of AppCourseProfiles
   * const count = await prisma.appCourseProfile.count({
   *   where: {
   *     // ... the filter for the AppCourseProfiles we want to count
   *   }
   * })
  **/
  count<T extends AppCourseProfileCountArgs>(
    args?: Prisma.Subset<T, AppCourseProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppCourseProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AppCourseProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCourseProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppCourseProfileAggregateArgs>(args: Prisma.Subset<T, AppCourseProfileAggregateArgs>): Prisma.PrismaPromise<GetAppCourseProfileAggregateType<T>>

  /**
   * Group by AppCourseProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppCourseProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppCourseProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppCourseProfileGroupByArgs['orderBy'] }
      : { orderBy?: AppCourseProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppCourseProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppCourseProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AppCourseProfile model
 */
readonly fields: AppCourseProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AppCourseProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppCourseProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  app<T extends Prisma.AppDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppDefaultArgs<ExtArgs>>): Prisma.Prisma__AppClient<runtime.Types.Result.GetResult<Prisma.$AppPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  modules<T extends Prisma.AppCourseProfile$modulesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppCourseProfile$modulesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CourseModulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  appFront<T extends Prisma.AppCourseProfile$appFrontArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppCourseProfile$appFrontArgs<ExtArgs>>): Prisma.Prisma__AppFrontClient<runtime.Types.Result.GetResult<Prisma.$AppFrontPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AppCourseProfile model
 */
export interface AppCourseProfileFieldRefs {
  readonly appId: Prisma.FieldRef<"AppCourseProfile", 'String'>
  readonly createdAt: Prisma.FieldRef<"AppCourseProfile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AppCourseProfile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AppCourseProfile findUnique
 */
export type AppCourseProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * Filter, which AppCourseProfile to fetch.
   */
  where: Prisma.AppCourseProfileWhereUniqueInput
}

/**
 * AppCourseProfile findUniqueOrThrow
 */
export type AppCourseProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * Filter, which AppCourseProfile to fetch.
   */
  where: Prisma.AppCourseProfileWhereUniqueInput
}

/**
 * AppCourseProfile findFirst
 */
export type AppCourseProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * Filter, which AppCourseProfile to fetch.
   */
  where?: Prisma.AppCourseProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCourseProfiles to fetch.
   */
  orderBy?: Prisma.AppCourseProfileOrderByWithRelationInput | Prisma.AppCourseProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppCourseProfiles.
   */
  cursor?: Prisma.AppCourseProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCourseProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCourseProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppCourseProfiles.
   */
  distinct?: Prisma.AppCourseProfileScalarFieldEnum | Prisma.AppCourseProfileScalarFieldEnum[]
}

/**
 * AppCourseProfile findFirstOrThrow
 */
export type AppCourseProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * Filter, which AppCourseProfile to fetch.
   */
  where?: Prisma.AppCourseProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCourseProfiles to fetch.
   */
  orderBy?: Prisma.AppCourseProfileOrderByWithRelationInput | Prisma.AppCourseProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppCourseProfiles.
   */
  cursor?: Prisma.AppCourseProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCourseProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCourseProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppCourseProfiles.
   */
  distinct?: Prisma.AppCourseProfileScalarFieldEnum | Prisma.AppCourseProfileScalarFieldEnum[]
}

/**
 * AppCourseProfile findMany
 */
export type AppCourseProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * Filter, which AppCourseProfiles to fetch.
   */
  where?: Prisma.AppCourseProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppCourseProfiles to fetch.
   */
  orderBy?: Prisma.AppCourseProfileOrderByWithRelationInput | Prisma.AppCourseProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AppCourseProfiles.
   */
  cursor?: Prisma.AppCourseProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppCourseProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppCourseProfiles.
   */
  skip?: number
  distinct?: Prisma.AppCourseProfileScalarFieldEnum | Prisma.AppCourseProfileScalarFieldEnum[]
}

/**
 * AppCourseProfile create
 */
export type AppCourseProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a AppCourseProfile.
   */
  data: Prisma.XOR<Prisma.AppCourseProfileCreateInput, Prisma.AppCourseProfileUncheckedCreateInput>
}

/**
 * AppCourseProfile createMany
 */
export type AppCourseProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AppCourseProfiles.
   */
  data: Prisma.AppCourseProfileCreateManyInput | Prisma.AppCourseProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AppCourseProfile createManyAndReturn
 */
export type AppCourseProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * The data used to create many AppCourseProfiles.
   */
  data: Prisma.AppCourseProfileCreateManyInput | Prisma.AppCourseProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AppCourseProfile update
 */
export type AppCourseProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a AppCourseProfile.
   */
  data: Prisma.XOR<Prisma.AppCourseProfileUpdateInput, Prisma.AppCourseProfileUncheckedUpdateInput>
  /**
   * Choose, which AppCourseProfile to update.
   */
  where: Prisma.AppCourseProfileWhereUniqueInput
}

/**
 * AppCourseProfile updateMany
 */
export type AppCourseProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AppCourseProfiles.
   */
  data: Prisma.XOR<Prisma.AppCourseProfileUpdateManyMutationInput, Prisma.AppCourseProfileUncheckedUpdateManyInput>
  /**
   * Filter which AppCourseProfiles to update
   */
  where?: Prisma.AppCourseProfileWhereInput
  /**
   * Limit how many AppCourseProfiles to update.
   */
  limit?: number
}

/**
 * AppCourseProfile updateManyAndReturn
 */
export type AppCourseProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * The data used to update AppCourseProfiles.
   */
  data: Prisma.XOR<Prisma.AppCourseProfileUpdateManyMutationInput, Prisma.AppCourseProfileUncheckedUpdateManyInput>
  /**
   * Filter which AppCourseProfiles to update
   */
  where?: Prisma.AppCourseProfileWhereInput
  /**
   * Limit how many AppCourseProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AppCourseProfile upsert
 */
export type AppCourseProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the AppCourseProfile to update in case it exists.
   */
  where: Prisma.AppCourseProfileWhereUniqueInput
  /**
   * In case the AppCourseProfile found by the `where` argument doesn't exist, create a new AppCourseProfile with this data.
   */
  create: Prisma.XOR<Prisma.AppCourseProfileCreateInput, Prisma.AppCourseProfileUncheckedCreateInput>
  /**
   * In case the AppCourseProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppCourseProfileUpdateInput, Prisma.AppCourseProfileUncheckedUpdateInput>
}

/**
 * AppCourseProfile delete
 */
export type AppCourseProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
  /**
   * Filter which AppCourseProfile to delete.
   */
  where: Prisma.AppCourseProfileWhereUniqueInput
}

/**
 * AppCourseProfile deleteMany
 */
export type AppCourseProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppCourseProfiles to delete
   */
  where?: Prisma.AppCourseProfileWhereInput
  /**
   * Limit how many AppCourseProfiles to delete.
   */
  limit?: number
}

/**
 * AppCourseProfile.modules
 */
export type AppCourseProfile$modulesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CourseModule
   */
  select?: Prisma.CourseModuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CourseModule
   */
  omit?: Prisma.CourseModuleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CourseModuleInclude<ExtArgs> | null
  where?: Prisma.CourseModuleWhereInput
  orderBy?: Prisma.CourseModuleOrderByWithRelationInput | Prisma.CourseModuleOrderByWithRelationInput[]
  cursor?: Prisma.CourseModuleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CourseModuleScalarFieldEnum | Prisma.CourseModuleScalarFieldEnum[]
}

/**
 * AppCourseProfile.appFront
 */
export type AppCourseProfile$appFrontArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppFront
   */
  select?: Prisma.AppFrontSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppFront
   */
  omit?: Prisma.AppFrontOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppFrontInclude<ExtArgs> | null
  where?: Prisma.AppFrontWhereInput
}

/**
 * AppCourseProfile without action
 */
export type AppCourseProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppCourseProfile
   */
  select?: Prisma.AppCourseProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppCourseProfile
   */
  omit?: Prisma.AppCourseProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppCourseProfileInclude<ExtArgs> | null
}
