
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CustomerLessonProgress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CustomerLessonProgress
 * 
 */
export type CustomerLessonProgressModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomerLessonProgressPayload>

export type AggregateCustomerLessonProgress = {
  _count: CustomerLessonProgressCountAggregateOutputType | null
  _min: CustomerLessonProgressMinAggregateOutputType | null
  _max: CustomerLessonProgressMaxAggregateOutputType | null
}

export type CustomerLessonProgressMinAggregateOutputType = {
  id: string | null
  customerId: string | null
  lessonId: string | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerLessonProgressMaxAggregateOutputType = {
  id: string | null
  customerId: string | null
  lessonId: string | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CustomerLessonProgressCountAggregateOutputType = {
  id: number
  customerId: number
  lessonId: number
  completedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CustomerLessonProgressMinAggregateInputType = {
  id?: true
  customerId?: true
  lessonId?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerLessonProgressMaxAggregateInputType = {
  id?: true
  customerId?: true
  lessonId?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type CustomerLessonProgressCountAggregateInputType = {
  id?: true
  customerId?: true
  lessonId?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CustomerLessonProgressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomerLessonProgress to aggregate.
   */
  where?: Prisma.CustomerLessonProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerLessonProgresses to fetch.
   */
  orderBy?: Prisma.CustomerLessonProgressOrderByWithRelationInput | Prisma.CustomerLessonProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomerLessonProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerLessonProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerLessonProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CustomerLessonProgresses
  **/
  _count?: true | CustomerLessonProgressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomerLessonProgressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomerLessonProgressMaxAggregateInputType
}

export type GetCustomerLessonProgressAggregateType<T extends CustomerLessonProgressAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomerLessonProgress]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomerLessonProgress[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomerLessonProgress[P]>
}




export type CustomerLessonProgressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomerLessonProgressWhereInput
  orderBy?: Prisma.CustomerLessonProgressOrderByWithAggregationInput | Prisma.CustomerLessonProgressOrderByWithAggregationInput[]
  by: Prisma.CustomerLessonProgressScalarFieldEnum[] | Prisma.CustomerLessonProgressScalarFieldEnum
  having?: Prisma.CustomerLessonProgressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomerLessonProgressCountAggregateInputType | true
  _min?: CustomerLessonProgressMinAggregateInputType
  _max?: CustomerLessonProgressMaxAggregateInputType
}

export type CustomerLessonProgressGroupByOutputType = {
  id: string
  customerId: string
  lessonId: string
  completedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: CustomerLessonProgressCountAggregateOutputType | null
  _min: CustomerLessonProgressMinAggregateOutputType | null
  _max: CustomerLessonProgressMaxAggregateOutputType | null
}

type GetCustomerLessonProgressGroupByPayload<T extends CustomerLessonProgressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomerLessonProgressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomerLessonProgressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomerLessonProgressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomerLessonProgressGroupByOutputType[P]>
      }
    >
  >



export type CustomerLessonProgressWhereInput = {
  AND?: Prisma.CustomerLessonProgressWhereInput | Prisma.CustomerLessonProgressWhereInput[]
  OR?: Prisma.CustomerLessonProgressWhereInput[]
  NOT?: Prisma.CustomerLessonProgressWhereInput | Prisma.CustomerLessonProgressWhereInput[]
  id?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  customerId?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  lessonId?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  completedAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  customer?: Prisma.XOR<Prisma.AppCustomerScalarRelationFilter, Prisma.AppCustomerWhereInput>
  lesson?: Prisma.XOR<Prisma.CourseLessonScalarRelationFilter, Prisma.CourseLessonWhereInput>
}

export type CustomerLessonProgressOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  customer?: Prisma.AppCustomerOrderByWithRelationInput
  lesson?: Prisma.CourseLessonOrderByWithRelationInput
}

export type CustomerLessonProgressWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  customerId_lessonId?: Prisma.CustomerLessonProgressCustomerIdLessonIdCompoundUniqueInput
  AND?: Prisma.CustomerLessonProgressWhereInput | Prisma.CustomerLessonProgressWhereInput[]
  OR?: Prisma.CustomerLessonProgressWhereInput[]
  NOT?: Prisma.CustomerLessonProgressWhereInput | Prisma.CustomerLessonProgressWhereInput[]
  customerId?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  lessonId?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  completedAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  customer?: Prisma.XOR<Prisma.AppCustomerScalarRelationFilter, Prisma.AppCustomerWhereInput>
  lesson?: Prisma.XOR<Prisma.CourseLessonScalarRelationFilter, Prisma.CourseLessonWhereInput>
}, "id" | "customerId_lessonId">

export type CustomerLessonProgressOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CustomerLessonProgressCountOrderByAggregateInput
  _max?: Prisma.CustomerLessonProgressMaxOrderByAggregateInput
  _min?: Prisma.CustomerLessonProgressMinOrderByAggregateInput
}

export type CustomerLessonProgressScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomerLessonProgressScalarWhereWithAggregatesInput | Prisma.CustomerLessonProgressScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomerLessonProgressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomerLessonProgressScalarWhereWithAggregatesInput | Prisma.CustomerLessonProgressScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CustomerLessonProgress"> | string
  customerId?: Prisma.StringWithAggregatesFilter<"CustomerLessonProgress"> | string
  lessonId?: Prisma.StringWithAggregatesFilter<"CustomerLessonProgress"> | string
  completedAt?: Prisma.DateTimeWithAggregatesFilter<"CustomerLessonProgress"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CustomerLessonProgress"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CustomerLessonProgress"> | Date | string
}

export type CustomerLessonProgressCreateInput = {
  id?: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.AppCustomerCreateNestedOneWithoutLessonProgressInput
  lesson: Prisma.CourseLessonCreateNestedOneWithoutLessonProgressInput
}

export type CustomerLessonProgressUncheckedCreateInput = {
  id?: string
  customerId: string
  lessonId: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerLessonProgressUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.AppCustomerUpdateOneRequiredWithoutLessonProgressNestedInput
  lesson?: Prisma.CourseLessonUpdateOneRequiredWithoutLessonProgressNestedInput
}

export type CustomerLessonProgressUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerLessonProgressCreateManyInput = {
  id?: string
  customerId: string
  lessonId: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerLessonProgressUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerLessonProgressUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerLessonProgressListRelationFilter = {
  every?: Prisma.CustomerLessonProgressWhereInput
  some?: Prisma.CustomerLessonProgressWhereInput
  none?: Prisma.CustomerLessonProgressWhereInput
}

export type CustomerLessonProgressOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CustomerLessonProgressCustomerIdLessonIdCompoundUniqueInput = {
  customerId: string
  lessonId: string
}

export type CustomerLessonProgressCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerLessonProgressMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerLessonProgressMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  lessonId?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CustomerLessonProgressCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput> | Prisma.CustomerLessonProgressCreateWithoutLessonInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyLessonInputEnvelope
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
}

export type CustomerLessonProgressUncheckedCreateNestedManyWithoutLessonInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput> | Prisma.CustomerLessonProgressCreateWithoutLessonInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyLessonInputEnvelope
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
}

export type CustomerLessonProgressUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput> | Prisma.CustomerLessonProgressCreateWithoutLessonInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutLessonInput | Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyLessonInputEnvelope
  set?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  disconnect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  delete?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  update?: Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutLessonInput | Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutLessonInput | Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.CustomerLessonProgressScalarWhereInput | Prisma.CustomerLessonProgressScalarWhereInput[]
}

export type CustomerLessonProgressUncheckedUpdateManyWithoutLessonNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput> | Prisma.CustomerLessonProgressCreateWithoutLessonInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutLessonInput[]
  upsert?: Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutLessonInput | Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutLessonInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyLessonInputEnvelope
  set?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  disconnect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  delete?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  update?: Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutLessonInput | Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutLessonInput[]
  updateMany?: Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutLessonInput | Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutLessonInput[]
  deleteMany?: Prisma.CustomerLessonProgressScalarWhereInput | Prisma.CustomerLessonProgressScalarWhereInput[]
}

export type CustomerLessonProgressCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput> | Prisma.CustomerLessonProgressCreateWithoutCustomerInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyCustomerInputEnvelope
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
}

export type CustomerLessonProgressUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput> | Prisma.CustomerLessonProgressCreateWithoutCustomerInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyCustomerInputEnvelope
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
}

export type CustomerLessonProgressUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput> | Prisma.CustomerLessonProgressCreateWithoutCustomerInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutCustomerInput | Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyCustomerInputEnvelope
  set?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  disconnect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  delete?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  update?: Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutCustomerInput | Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutCustomerInput | Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.CustomerLessonProgressScalarWhereInput | Prisma.CustomerLessonProgressScalarWhereInput[]
}

export type CustomerLessonProgressUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput> | Prisma.CustomerLessonProgressCreateWithoutCustomerInput[] | Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput | Prisma.CustomerLessonProgressCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutCustomerInput | Prisma.CustomerLessonProgressUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.CustomerLessonProgressCreateManyCustomerInputEnvelope
  set?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  disconnect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  delete?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  connect?: Prisma.CustomerLessonProgressWhereUniqueInput | Prisma.CustomerLessonProgressWhereUniqueInput[]
  update?: Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutCustomerInput | Prisma.CustomerLessonProgressUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutCustomerInput | Prisma.CustomerLessonProgressUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.CustomerLessonProgressScalarWhereInput | Prisma.CustomerLessonProgressScalarWhereInput[]
}

export type CustomerLessonProgressCreateWithoutLessonInput = {
  id?: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  customer: Prisma.AppCustomerCreateNestedOneWithoutLessonProgressInput
}

export type CustomerLessonProgressUncheckedCreateWithoutLessonInput = {
  id?: string
  customerId: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerLessonProgressCreateOrConnectWithoutLessonInput = {
  where: Prisma.CustomerLessonProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput>
}

export type CustomerLessonProgressCreateManyLessonInputEnvelope = {
  data: Prisma.CustomerLessonProgressCreateManyLessonInput | Prisma.CustomerLessonProgressCreateManyLessonInput[]
  skipDuplicates?: boolean
}

export type CustomerLessonProgressUpsertWithWhereUniqueWithoutLessonInput = {
  where: Prisma.CustomerLessonProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.CustomerLessonProgressUpdateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedUpdateWithoutLessonInput>
  create: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutLessonInput>
}

export type CustomerLessonProgressUpdateWithWhereUniqueWithoutLessonInput = {
  where: Prisma.CustomerLessonProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.CustomerLessonProgressUpdateWithoutLessonInput, Prisma.CustomerLessonProgressUncheckedUpdateWithoutLessonInput>
}

export type CustomerLessonProgressUpdateManyWithWhereWithoutLessonInput = {
  where: Prisma.CustomerLessonProgressScalarWhereInput
  data: Prisma.XOR<Prisma.CustomerLessonProgressUpdateManyMutationInput, Prisma.CustomerLessonProgressUncheckedUpdateManyWithoutLessonInput>
}

export type CustomerLessonProgressScalarWhereInput = {
  AND?: Prisma.CustomerLessonProgressScalarWhereInput | Prisma.CustomerLessonProgressScalarWhereInput[]
  OR?: Prisma.CustomerLessonProgressScalarWhereInput[]
  NOT?: Prisma.CustomerLessonProgressScalarWhereInput | Prisma.CustomerLessonProgressScalarWhereInput[]
  id?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  customerId?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  lessonId?: Prisma.StringFilter<"CustomerLessonProgress"> | string
  completedAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CustomerLessonProgress"> | Date | string
}

export type CustomerLessonProgressCreateWithoutCustomerInput = {
  id?: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  lesson: Prisma.CourseLessonCreateNestedOneWithoutLessonProgressInput
}

export type CustomerLessonProgressUncheckedCreateWithoutCustomerInput = {
  id?: string
  lessonId: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerLessonProgressCreateOrConnectWithoutCustomerInput = {
  where: Prisma.CustomerLessonProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput>
}

export type CustomerLessonProgressCreateManyCustomerInputEnvelope = {
  data: Prisma.CustomerLessonProgressCreateManyCustomerInput | Prisma.CustomerLessonProgressCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type CustomerLessonProgressUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.CustomerLessonProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.CustomerLessonProgressUpdateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.CustomerLessonProgressCreateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedCreateWithoutCustomerInput>
}

export type CustomerLessonProgressUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.CustomerLessonProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.CustomerLessonProgressUpdateWithoutCustomerInput, Prisma.CustomerLessonProgressUncheckedUpdateWithoutCustomerInput>
}

export type CustomerLessonProgressUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.CustomerLessonProgressScalarWhereInput
  data: Prisma.XOR<Prisma.CustomerLessonProgressUpdateManyMutationInput, Prisma.CustomerLessonProgressUncheckedUpdateManyWithoutCustomerInput>
}

export type CustomerLessonProgressCreateManyLessonInput = {
  id?: string
  customerId: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerLessonProgressUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.AppCustomerUpdateOneRequiredWithoutLessonProgressNestedInput
}

export type CustomerLessonProgressUncheckedUpdateWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerLessonProgressUncheckedUpdateManyWithoutLessonInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerLessonProgressCreateManyCustomerInput = {
  id?: string
  lessonId: string
  completedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CustomerLessonProgressUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lesson?: Prisma.CourseLessonUpdateOneRequiredWithoutLessonProgressNestedInput
}

export type CustomerLessonProgressUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerLessonProgressUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  lessonId?: Prisma.StringFieldUpdateOperationsInput | string
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CustomerLessonProgressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerId?: boolean
  lessonId?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.AppCustomerDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.CourseLessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerLessonProgress"]>

export type CustomerLessonProgressSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerId?: boolean
  lessonId?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.AppCustomerDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.CourseLessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerLessonProgress"]>

export type CustomerLessonProgressSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerId?: boolean
  lessonId?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  customer?: boolean | Prisma.AppCustomerDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.CourseLessonDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerLessonProgress"]>

export type CustomerLessonProgressSelectScalar = {
  id?: boolean
  customerId?: boolean
  lessonId?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CustomerLessonProgressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "customerId" | "lessonId" | "completedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["customerLessonProgress"]>
export type CustomerLessonProgressInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.AppCustomerDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.CourseLessonDefaultArgs<ExtArgs>
}
export type CustomerLessonProgressIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.AppCustomerDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.CourseLessonDefaultArgs<ExtArgs>
}
export type CustomerLessonProgressIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.AppCustomerDefaultArgs<ExtArgs>
  lesson?: boolean | Prisma.CourseLessonDefaultArgs<ExtArgs>
}

export type $CustomerLessonProgressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CustomerLessonProgress"
  objects: {
    customer: Prisma.$AppCustomerPayload<ExtArgs>
    lesson: Prisma.$CourseLessonPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    customerId: string
    lessonId: string
    completedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["customerLessonProgress"]>
  composites: {}
}

export type CustomerLessonProgressGetPayload<S extends boolean | null | undefined | CustomerLessonProgressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload, S>

export type CustomerLessonProgressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomerLessonProgressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomerLessonProgressCountAggregateInputType | true
  }

export interface CustomerLessonProgressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CustomerLessonProgress'], meta: { name: 'CustomerLessonProgress' } }
  /**
   * Find zero or one CustomerLessonProgress that matches the filter.
   * @param {CustomerLessonProgressFindUniqueArgs} args - Arguments to find a CustomerLessonProgress
   * @example
   * // Get one CustomerLessonProgress
   * const customerLessonProgress = await prisma.customerLessonProgress.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomerLessonProgressFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CustomerLessonProgress that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomerLessonProgressFindUniqueOrThrowArgs} args - Arguments to find a CustomerLessonProgress
   * @example
   * // Get one CustomerLessonProgress
   * const customerLessonProgress = await prisma.customerLessonProgress.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomerLessonProgressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomerLessonProgress that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerLessonProgressFindFirstArgs} args - Arguments to find a CustomerLessonProgress
   * @example
   * // Get one CustomerLessonProgress
   * const customerLessonProgress = await prisma.customerLessonProgress.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomerLessonProgressFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomerLessonProgressFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomerLessonProgress that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerLessonProgressFindFirstOrThrowArgs} args - Arguments to find a CustomerLessonProgress
   * @example
   * // Get one CustomerLessonProgress
   * const customerLessonProgress = await prisma.customerLessonProgress.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomerLessonProgressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomerLessonProgressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CustomerLessonProgresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerLessonProgressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CustomerLessonProgresses
   * const customerLessonProgresses = await prisma.customerLessonProgress.findMany()
   * 
   * // Get first 10 CustomerLessonProgresses
   * const customerLessonProgresses = await prisma.customerLessonProgress.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customerLessonProgressWithIdOnly = await prisma.customerLessonProgress.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomerLessonProgressFindManyArgs>(args?: Prisma.SelectSubset<T, CustomerLessonProgressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CustomerLessonProgress.
   * @param {CustomerLessonProgressCreateArgs} args - Arguments to create a CustomerLessonProgress.
   * @example
   * // Create one CustomerLessonProgress
   * const CustomerLessonProgress = await prisma.customerLessonProgress.create({
   *   data: {
   *     // ... data to create a CustomerLessonProgress
   *   }
   * })
   * 
   */
  create<T extends CustomerLessonProgressCreateArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressCreateArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CustomerLessonProgresses.
   * @param {CustomerLessonProgressCreateManyArgs} args - Arguments to create many CustomerLessonProgresses.
   * @example
   * // Create many CustomerLessonProgresses
   * const customerLessonProgress = await prisma.customerLessonProgress.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomerLessonProgressCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomerLessonProgressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CustomerLessonProgresses and returns the data saved in the database.
   * @param {CustomerLessonProgressCreateManyAndReturnArgs} args - Arguments to create many CustomerLessonProgresses.
   * @example
   * // Create many CustomerLessonProgresses
   * const customerLessonProgress = await prisma.customerLessonProgress.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CustomerLessonProgresses and only return the `id`
   * const customerLessonProgressWithIdOnly = await prisma.customerLessonProgress.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomerLessonProgressCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomerLessonProgressCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CustomerLessonProgress.
   * @param {CustomerLessonProgressDeleteArgs} args - Arguments to delete one CustomerLessonProgress.
   * @example
   * // Delete one CustomerLessonProgress
   * const CustomerLessonProgress = await prisma.customerLessonProgress.delete({
   *   where: {
   *     // ... filter to delete one CustomerLessonProgress
   *   }
   * })
   * 
   */
  delete<T extends CustomerLessonProgressDeleteArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CustomerLessonProgress.
   * @param {CustomerLessonProgressUpdateArgs} args - Arguments to update one CustomerLessonProgress.
   * @example
   * // Update one CustomerLessonProgress
   * const customerLessonProgress = await prisma.customerLessonProgress.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomerLessonProgressUpdateArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CustomerLessonProgresses.
   * @param {CustomerLessonProgressDeleteManyArgs} args - Arguments to filter CustomerLessonProgresses to delete.
   * @example
   * // Delete a few CustomerLessonProgresses
   * const { count } = await prisma.customerLessonProgress.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomerLessonProgressDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomerLessonProgressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomerLessonProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerLessonProgressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CustomerLessonProgresses
   * const customerLessonProgress = await prisma.customerLessonProgress.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomerLessonProgressUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomerLessonProgresses and returns the data updated in the database.
   * @param {CustomerLessonProgressUpdateManyAndReturnArgs} args - Arguments to update many CustomerLessonProgresses.
   * @example
   * // Update many CustomerLessonProgresses
   * const customerLessonProgress = await prisma.customerLessonProgress.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CustomerLessonProgresses and only return the `id`
   * const customerLessonProgressWithIdOnly = await prisma.customerLessonProgress.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomerLessonProgressUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CustomerLessonProgress.
   * @param {CustomerLessonProgressUpsertArgs} args - Arguments to update or create a CustomerLessonProgress.
   * @example
   * // Update or create a CustomerLessonProgress
   * const customerLessonProgress = await prisma.customerLessonProgress.upsert({
   *   create: {
   *     // ... data to create a CustomerLessonProgress
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CustomerLessonProgress we want to update
   *   }
   * })
   */
  upsert<T extends CustomerLessonProgressUpsertArgs>(args: Prisma.SelectSubset<T, CustomerLessonProgressUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomerLessonProgressClient<runtime.Types.Result.GetResult<Prisma.$CustomerLessonProgressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CustomerLessonProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerLessonProgressCountArgs} args - Arguments to filter CustomerLessonProgresses to count.
   * @example
   * // Count the number of CustomerLessonProgresses
   * const count = await prisma.customerLessonProgress.count({
   *   where: {
   *     // ... the filter for the CustomerLessonProgresses we want to count
   *   }
   * })
  **/
  count<T extends CustomerLessonProgressCountArgs>(
    args?: Prisma.Subset<T, CustomerLessonProgressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomerLessonProgressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CustomerLessonProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerLessonProgressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomerLessonProgressAggregateArgs>(args: Prisma.Subset<T, CustomerLessonProgressAggregateArgs>): Prisma.PrismaPromise<GetCustomerLessonProgressAggregateType<T>>

  /**
   * Group by CustomerLessonProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerLessonProgressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomerLessonProgressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomerLessonProgressGroupByArgs['orderBy'] }
      : { orderBy?: CustomerLessonProgressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomerLessonProgressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomerLessonProgressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CustomerLessonProgress model
 */
readonly fields: CustomerLessonProgressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CustomerLessonProgress.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomerLessonProgressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  customer<T extends Prisma.AppCustomerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppCustomerDefaultArgs<ExtArgs>>): Prisma.Prisma__AppCustomerClient<runtime.Types.Result.GetResult<Prisma.$AppCustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  lesson<T extends Prisma.CourseLessonDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseLessonDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseLessonClient<runtime.Types.Result.GetResult<Prisma.$CourseLessonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CustomerLessonProgress model
 */
export interface CustomerLessonProgressFieldRefs {
  readonly id: Prisma.FieldRef<"CustomerLessonProgress", 'String'>
  readonly customerId: Prisma.FieldRef<"CustomerLessonProgress", 'String'>
  readonly lessonId: Prisma.FieldRef<"CustomerLessonProgress", 'String'>
  readonly completedAt: Prisma.FieldRef<"CustomerLessonProgress", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"CustomerLessonProgress", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CustomerLessonProgress", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CustomerLessonProgress findUnique
 */
export type CustomerLessonProgressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * Filter, which CustomerLessonProgress to fetch.
   */
  where: Prisma.CustomerLessonProgressWhereUniqueInput
}

/**
 * CustomerLessonProgress findUniqueOrThrow
 */
export type CustomerLessonProgressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * Filter, which CustomerLessonProgress to fetch.
   */
  where: Prisma.CustomerLessonProgressWhereUniqueInput
}

/**
 * CustomerLessonProgress findFirst
 */
export type CustomerLessonProgressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * Filter, which CustomerLessonProgress to fetch.
   */
  where?: Prisma.CustomerLessonProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerLessonProgresses to fetch.
   */
  orderBy?: Prisma.CustomerLessonProgressOrderByWithRelationInput | Prisma.CustomerLessonProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomerLessonProgresses.
   */
  cursor?: Prisma.CustomerLessonProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerLessonProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerLessonProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerLessonProgresses.
   */
  distinct?: Prisma.CustomerLessonProgressScalarFieldEnum | Prisma.CustomerLessonProgressScalarFieldEnum[]
}

/**
 * CustomerLessonProgress findFirstOrThrow
 */
export type CustomerLessonProgressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * Filter, which CustomerLessonProgress to fetch.
   */
  where?: Prisma.CustomerLessonProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerLessonProgresses to fetch.
   */
  orderBy?: Prisma.CustomerLessonProgressOrderByWithRelationInput | Prisma.CustomerLessonProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomerLessonProgresses.
   */
  cursor?: Prisma.CustomerLessonProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerLessonProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerLessonProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerLessonProgresses.
   */
  distinct?: Prisma.CustomerLessonProgressScalarFieldEnum | Prisma.CustomerLessonProgressScalarFieldEnum[]
}

/**
 * CustomerLessonProgress findMany
 */
export type CustomerLessonProgressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * Filter, which CustomerLessonProgresses to fetch.
   */
  where?: Prisma.CustomerLessonProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerLessonProgresses to fetch.
   */
  orderBy?: Prisma.CustomerLessonProgressOrderByWithRelationInput | Prisma.CustomerLessonProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CustomerLessonProgresses.
   */
  cursor?: Prisma.CustomerLessonProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerLessonProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerLessonProgresses.
   */
  skip?: number
  distinct?: Prisma.CustomerLessonProgressScalarFieldEnum | Prisma.CustomerLessonProgressScalarFieldEnum[]
}

/**
 * CustomerLessonProgress create
 */
export type CustomerLessonProgressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * The data needed to create a CustomerLessonProgress.
   */
  data: Prisma.XOR<Prisma.CustomerLessonProgressCreateInput, Prisma.CustomerLessonProgressUncheckedCreateInput>
}

/**
 * CustomerLessonProgress createMany
 */
export type CustomerLessonProgressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CustomerLessonProgresses.
   */
  data: Prisma.CustomerLessonProgressCreateManyInput | Prisma.CustomerLessonProgressCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CustomerLessonProgress createManyAndReturn
 */
export type CustomerLessonProgressCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * The data used to create many CustomerLessonProgresses.
   */
  data: Prisma.CustomerLessonProgressCreateManyInput | Prisma.CustomerLessonProgressCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CustomerLessonProgress update
 */
export type CustomerLessonProgressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * The data needed to update a CustomerLessonProgress.
   */
  data: Prisma.XOR<Prisma.CustomerLessonProgressUpdateInput, Prisma.CustomerLessonProgressUncheckedUpdateInput>
  /**
   * Choose, which CustomerLessonProgress to update.
   */
  where: Prisma.CustomerLessonProgressWhereUniqueInput
}

/**
 * CustomerLessonProgress updateMany
 */
export type CustomerLessonProgressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CustomerLessonProgresses.
   */
  data: Prisma.XOR<Prisma.CustomerLessonProgressUpdateManyMutationInput, Prisma.CustomerLessonProgressUncheckedUpdateManyInput>
  /**
   * Filter which CustomerLessonProgresses to update
   */
  where?: Prisma.CustomerLessonProgressWhereInput
  /**
   * Limit how many CustomerLessonProgresses to update.
   */
  limit?: number
}

/**
 * CustomerLessonProgress updateManyAndReturn
 */
export type CustomerLessonProgressUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * The data used to update CustomerLessonProgresses.
   */
  data: Prisma.XOR<Prisma.CustomerLessonProgressUpdateManyMutationInput, Prisma.CustomerLessonProgressUncheckedUpdateManyInput>
  /**
   * Filter which CustomerLessonProgresses to update
   */
  where?: Prisma.CustomerLessonProgressWhereInput
  /**
   * Limit how many CustomerLessonProgresses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CustomerLessonProgress upsert
 */
export type CustomerLessonProgressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * The filter to search for the CustomerLessonProgress to update in case it exists.
   */
  where: Prisma.CustomerLessonProgressWhereUniqueInput
  /**
   * In case the CustomerLessonProgress found by the `where` argument doesn't exist, create a new CustomerLessonProgress with this data.
   */
  create: Prisma.XOR<Prisma.CustomerLessonProgressCreateInput, Prisma.CustomerLessonProgressUncheckedCreateInput>
  /**
   * In case the CustomerLessonProgress was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomerLessonProgressUpdateInput, Prisma.CustomerLessonProgressUncheckedUpdateInput>
}

/**
 * CustomerLessonProgress delete
 */
export type CustomerLessonProgressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
  /**
   * Filter which CustomerLessonProgress to delete.
   */
  where: Prisma.CustomerLessonProgressWhereUniqueInput
}

/**
 * CustomerLessonProgress deleteMany
 */
export type CustomerLessonProgressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomerLessonProgresses to delete
   */
  where?: Prisma.CustomerLessonProgressWhereInput
  /**
   * Limit how many CustomerLessonProgresses to delete.
   */
  limit?: number
}

/**
 * CustomerLessonProgress without action
 */
export type CustomerLessonProgressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerLessonProgress
   */
  select?: Prisma.CustomerLessonProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerLessonProgress
   */
  omit?: Prisma.CustomerLessonProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerLessonProgressInclude<ExtArgs> | null
}
