// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/webhooks/lemon-squeezy": {
    params: {};
  };
  "/auth/callback/google": {
    params: {};
  };
  "/api/cache-status": {
    params: {};
  };
  "/learn/content": {
    params: {};
  };
  "/api/purchase": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/auth/verify": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/preview": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/refund": {
    params: {};
  };
  "/learn": {
    params: {};
  };
  "/learn/:moduleSlug/:lessonSlug": {
    params: {
      "moduleSlug": string;
      "lessonSlug": string;
    };
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/webhooks/lemon-squeezy" | "/auth/callback/google" | "/api/cache-status" | "/learn/content" | "/api/purchase" | "/auth/logout" | "/auth/verify" | "/auth/login" | "/preview" | "/privacy" | "/refund" | "/learn" | "/learn/:moduleSlug/:lessonSlug" | "/terms" | "/*";
  };
  "routes/api.webhooks.lemon-squeezy.tsx": {
    id: "routes/api.webhooks.lemon-squeezy";
    page: "/api/webhooks/lemon-squeezy";
  };
  "routes/auth.callback.google.tsx": {
    id: "routes/auth.callback.google";
    page: "/auth/callback/google";
  };
  "routes/api.cache-status.tsx": {
    id: "routes/api.cache-status";
    page: "/api/cache-status";
  };
  "routes/learn_.content/route.tsx": {
    id: "routes/learn_.content";
    page: "/learn/content";
  };
  "routes/api.purchase.tsx": {
    id: "routes/api.purchase";
    page: "/api/purchase";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/auth.verify.tsx": {
    id: "routes/auth.verify";
    page: "/auth/verify";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/preview/route.tsx": {
    id: "routes/preview";
    page: "/preview";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/refund.tsx": {
    id: "routes/refund";
    page: "/refund";
  };
  "routes/learn/route.tsx": {
    id: "routes/learn";
    page: "/learn" | "/learn/:moduleSlug/:lessonSlug";
  };
  "routes/learn.$moduleSlug.$lessonSlug/route.tsx": {
    id: "routes/learn.$moduleSlug.$lessonSlug";
    page: "/learn/:moduleSlug/:lessonSlug";
  };
  "routes/learn.$moduleSlug.$lessonSlug._index/route.tsx": {
    id: "routes/learn.$moduleSlug.$lessonSlug._index";
    page: "/learn/:moduleSlug/:lessonSlug";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.webhooks.lemon-squeezy": typeof import("./app/routes/api.webhooks.lemon-squeezy.tsx");
  "routes/auth.callback.google": typeof import("./app/routes/auth.callback.google.tsx");
  "routes/api.cache-status": typeof import("./app/routes/api.cache-status.tsx");
  "routes/learn_.content": typeof import("./app/routes/learn_.content/route.tsx");
  "routes/api.purchase": typeof import("./app/routes/api.purchase.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/auth.verify": typeof import("./app/routes/auth.verify.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/preview": typeof import("./app/routes/preview/route.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/refund": typeof import("./app/routes/refund.tsx");
  "routes/learn": typeof import("./app/routes/learn/route.tsx");
  "routes/learn.$moduleSlug.$lessonSlug": typeof import("./app/routes/learn.$moduleSlug.$lessonSlug/route.tsx");
  "routes/learn.$moduleSlug.$lessonSlug._index": typeof import("./app/routes/learn.$moduleSlug.$lessonSlug._index/route.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};