
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `entrance_exams` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model entrance_exams
 * 
 */
export type entrance_examsModel = runtime.Types.Result.DefaultSelection<Prisma.$entrance_examsPayload>

export type AggregateEntrance_exams = {
  _count: Entrance_examsCountAggregateOutputType | null
  _avg: Entrance_examsAvgAggregateOutputType | null
  _sum: Entrance_examsSumAggregateOutputType | null
  _min: Entrance_examsMinAggregateOutputType | null
  _max: Entrance_examsMaxAggregateOutputType | null
}

export type Entrance_examsAvgAggregateOutputType = {
  year: number | null
  order: number | null
}

export type Entrance_examsSumAggregateOutputType = {
  year: number | null
  order: number | null
}

export type Entrance_examsMinAggregateOutputType = {
  id: string | null
  title: string | null
  year: number | null
  subject: string | null
  type: string | null
  description: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Entrance_examsMaxAggregateOutputType = {
  id: string | null
  title: string | null
  year: number | null
  subject: string | null
  type: string | null
  description: string | null
  order: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Entrance_examsCountAggregateOutputType = {
  id: number
  title: number
  year: number
  subject: number
  type: number
  description: number
  order: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type Entrance_examsAvgAggregateInputType = {
  year?: true
  order?: true
}

export type Entrance_examsSumAggregateInputType = {
  year?: true
  order?: true
}

export type Entrance_examsMinAggregateInputType = {
  id?: true
  title?: true
  year?: true
  subject?: true
  type?: true
  description?: true
  order?: true
  createdAt?: true
  updatedAt?: true
}

export type Entrance_examsMaxAggregateInputType = {
  id?: true
  title?: true
  year?: true
  subject?: true
  type?: true
  description?: true
  order?: true
  createdAt?: true
  updatedAt?: true
}

export type Entrance_examsCountAggregateInputType = {
  id?: true
  title?: true
  year?: true
  subject?: true
  type?: true
  description?: true
  order?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type Entrance_examsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which entrance_exams to aggregate.
   */
  where?: Prisma.entrance_examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entrance_exams to fetch.
   */
  orderBy?: Prisma.entrance_examsOrderByWithRelationInput | Prisma.entrance_examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.entrance_examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entrance_exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entrance_exams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned entrance_exams
  **/
  _count?: true | Entrance_examsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Entrance_examsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Entrance_examsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Entrance_examsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Entrance_examsMaxAggregateInputType
}

export type GetEntrance_examsAggregateType<T extends Entrance_examsAggregateArgs> = {
      [P in keyof T & keyof AggregateEntrance_exams]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEntrance_exams[P]>
    : Prisma.GetScalarType<T[P], AggregateEntrance_exams[P]>
}




export type entrance_examsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.entrance_examsWhereInput
  orderBy?: Prisma.entrance_examsOrderByWithAggregationInput | Prisma.entrance_examsOrderByWithAggregationInput[]
  by: Prisma.Entrance_examsScalarFieldEnum[] | Prisma.Entrance_examsScalarFieldEnum
  having?: Prisma.entrance_examsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Entrance_examsCountAggregateInputType | true
  _avg?: Entrance_examsAvgAggregateInputType
  _sum?: Entrance_examsSumAggregateInputType
  _min?: Entrance_examsMinAggregateInputType
  _max?: Entrance_examsMaxAggregateInputType
}

export type Entrance_examsGroupByOutputType = {
  id: string
  title: string
  year: number
  subject: string
  type: string
  description: string | null
  order: number
  createdAt: Date
  updatedAt: Date
  _count: Entrance_examsCountAggregateOutputType | null
  _avg: Entrance_examsAvgAggregateOutputType | null
  _sum: Entrance_examsSumAggregateOutputType | null
  _min: Entrance_examsMinAggregateOutputType | null
  _max: Entrance_examsMaxAggregateOutputType | null
}

type GetEntrance_examsGroupByPayload<T extends entrance_examsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Entrance_examsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Entrance_examsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Entrance_examsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Entrance_examsGroupByOutputType[P]>
      }
    >
  > 



export type entrance_examsWhereInput = {
  AND?: Prisma.entrance_examsWhereInput | Prisma.entrance_examsWhereInput[]
  OR?: Prisma.entrance_examsWhereInput[]
  NOT?: Prisma.entrance_examsWhereInput | Prisma.entrance_examsWhereInput[]
  id?: Prisma.StringFilter<"entrance_exams"> | string
  title?: Prisma.StringFilter<"entrance_exams"> | string
  year?: Prisma.IntFilter<"entrance_exams"> | number
  subject?: Prisma.StringFilter<"entrance_exams"> | string
  type?: Prisma.StringFilter<"entrance_exams"> | string
  description?: Prisma.StringNullableFilter<"entrance_exams"> | string | null
  order?: Prisma.IntFilter<"entrance_exams"> | number
  createdAt?: Prisma.DateTimeFilter<"entrance_exams"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"entrance_exams"> | Date | string
  exam_questions?: Prisma.Exam_questionsListRelationFilter
}

export type entrance_examsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  year?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  exam_questions?: Prisma.exam_questionsOrderByRelationAggregateInput
}

export type entrance_examsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.entrance_examsWhereInput | Prisma.entrance_examsWhereInput[]
  OR?: Prisma.entrance_examsWhereInput[]
  NOT?: Prisma.entrance_examsWhereInput | Prisma.entrance_examsWhereInput[]
  title?: Prisma.StringFilter<"entrance_exams"> | string
  year?: Prisma.IntFilter<"entrance_exams"> | number
  subject?: Prisma.StringFilter<"entrance_exams"> | string
  type?: Prisma.StringFilter<"entrance_exams"> | string
  description?: Prisma.StringNullableFilter<"entrance_exams"> | string | null
  order?: Prisma.IntFilter<"entrance_exams"> | number
  createdAt?: Prisma.DateTimeFilter<"entrance_exams"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"entrance_exams"> | Date | string
  exam_questions?: Prisma.Exam_questionsListRelationFilter
}, "id">

export type entrance_examsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  year?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.entrance_examsCountOrderByAggregateInput
  _avg?: Prisma.entrance_examsAvgOrderByAggregateInput
  _max?: Prisma.entrance_examsMaxOrderByAggregateInput
  _min?: Prisma.entrance_examsMinOrderByAggregateInput
  _sum?: Prisma.entrance_examsSumOrderByAggregateInput
}

export type entrance_examsScalarWhereWithAggregatesInput = {
  AND?: Prisma.entrance_examsScalarWhereWithAggregatesInput | Prisma.entrance_examsScalarWhereWithAggregatesInput[]
  OR?: Prisma.entrance_examsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.entrance_examsScalarWhereWithAggregatesInput | Prisma.entrance_examsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"entrance_exams"> | string
  title?: Prisma.StringWithAggregatesFilter<"entrance_exams"> | string
  year?: Prisma.IntWithAggregatesFilter<"entrance_exams"> | number
  subject?: Prisma.StringWithAggregatesFilter<"entrance_exams"> | string
  type?: Prisma.StringWithAggregatesFilter<"entrance_exams"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"entrance_exams"> | string | null
  order?: Prisma.IntWithAggregatesFilter<"entrance_exams"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"entrance_exams"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"entrance_exams"> | Date | string
}

export type entrance_examsCreateInput = {
  id: string
  title: string
  year: number
  subject: string
  type: string
  description?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
  exam_questions?: Prisma.exam_questionsCreateNestedManyWithoutEntrance_examsInput
}

export type entrance_examsUncheckedCreateInput = {
  id: string
  title: string
  year: number
  subject: string
  type: string
  description?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
  exam_questions?: Prisma.exam_questionsUncheckedCreateNestedManyWithoutEntrance_examsInput
}

export type entrance_examsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exam_questions?: Prisma.exam_questionsUpdateManyWithoutEntrance_examsNestedInput
}

export type entrance_examsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exam_questions?: Prisma.exam_questionsUncheckedUpdateManyWithoutEntrance_examsNestedInput
}

export type entrance_examsCreateManyInput = {
  id: string
  title: string
  year: number
  subject: string
  type: string
  description?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type entrance_examsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type entrance_examsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type entrance_examsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  year?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type entrance_examsAvgOrderByAggregateInput = {
  year?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type entrance_examsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  year?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type entrance_examsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  year?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type entrance_examsSumOrderByAggregateInput = {
  year?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type Entrance_examsScalarRelationFilter = {
  is?: Prisma.entrance_examsWhereInput
  isNot?: Prisma.entrance_examsWhereInput
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type entrance_examsCreateNestedOneWithoutExam_questionsInput = {
  create?: Prisma.XOR<Prisma.entrance_examsCreateWithoutExam_questionsInput, Prisma.entrance_examsUncheckedCreateWithoutExam_questionsInput>
  connectOrCreate?: Prisma.entrance_examsCreateOrConnectWithoutExam_questionsInput
  connect?: Prisma.entrance_examsWhereUniqueInput
}

export type entrance_examsUpdateOneRequiredWithoutExam_questionsNestedInput = {
  create?: Prisma.XOR<Prisma.entrance_examsCreateWithoutExam_questionsInput, Prisma.entrance_examsUncheckedCreateWithoutExam_questionsInput>
  connectOrCreate?: Prisma.entrance_examsCreateOrConnectWithoutExam_questionsInput
  upsert?: Prisma.entrance_examsUpsertWithoutExam_questionsInput
  connect?: Prisma.entrance_examsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.entrance_examsUpdateToOneWithWhereWithoutExam_questionsInput, Prisma.entrance_examsUpdateWithoutExam_questionsInput>, Prisma.entrance_examsUncheckedUpdateWithoutExam_questionsInput>
}

export type entrance_examsCreateWithoutExam_questionsInput = {
  id: string
  title: string
  year: number
  subject: string
  type: string
  description?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type entrance_examsUncheckedCreateWithoutExam_questionsInput = {
  id: string
  title: string
  year: number
  subject: string
  type: string
  description?: string | null
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type entrance_examsCreateOrConnectWithoutExam_questionsInput = {
  where: Prisma.entrance_examsWhereUniqueInput
  create: Prisma.XOR<Prisma.entrance_examsCreateWithoutExam_questionsInput, Prisma.entrance_examsUncheckedCreateWithoutExam_questionsInput>
}

export type entrance_examsUpsertWithoutExam_questionsInput = {
  update: Prisma.XOR<Prisma.entrance_examsUpdateWithoutExam_questionsInput, Prisma.entrance_examsUncheckedUpdateWithoutExam_questionsInput>
  create: Prisma.XOR<Prisma.entrance_examsCreateWithoutExam_questionsInput, Prisma.entrance_examsUncheckedCreateWithoutExam_questionsInput>
  where?: Prisma.entrance_examsWhereInput
}

export type entrance_examsUpdateToOneWithWhereWithoutExam_questionsInput = {
  where?: Prisma.entrance_examsWhereInput
  data: Prisma.XOR<Prisma.entrance_examsUpdateWithoutExam_questionsInput, Prisma.entrance_examsUncheckedUpdateWithoutExam_questionsInput>
}

export type entrance_examsUpdateWithoutExam_questionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type entrance_examsUncheckedUpdateWithoutExam_questionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  year?: Prisma.IntFieldUpdateOperationsInput | number
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type Entrance_examsCountOutputType
 */

export type Entrance_examsCountOutputType = {
  exam_questions: number
}

export type Entrance_examsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  exam_questions?: boolean | Entrance_examsCountOutputTypeCountExam_questionsArgs
}

/**
 * Entrance_examsCountOutputType without action
 */
export type Entrance_examsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entrance_examsCountOutputType
   */
  select?: Prisma.Entrance_examsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Entrance_examsCountOutputType without action
 */
export type Entrance_examsCountOutputTypeCountExam_questionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.exam_questionsWhereInput
}


export type entrance_examsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  year?: boolean
  subject?: boolean
  type?: boolean
  description?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  exam_questions?: boolean | Prisma.entrance_exams$exam_questionsArgs<ExtArgs>
  _count?: boolean | Prisma.Entrance_examsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["entrance_exams"]>

export type entrance_examsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  year?: boolean
  subject?: boolean
  type?: boolean
  description?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["entrance_exams"]>

export type entrance_examsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  year?: boolean
  subject?: boolean
  type?: boolean
  description?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["entrance_exams"]>

export type entrance_examsSelectScalar = {
  id?: boolean
  title?: boolean
  year?: boolean
  subject?: boolean
  type?: boolean
  description?: boolean
  order?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type entrance_examsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "year" | "subject" | "type" | "description" | "order" | "createdAt" | "updatedAt", ExtArgs["result"]["entrance_exams"]>
export type entrance_examsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  exam_questions?: boolean | Prisma.entrance_exams$exam_questionsArgs<ExtArgs>
  _count?: boolean | Prisma.Entrance_examsCountOutputTypeDefaultArgs<ExtArgs>
}
export type entrance_examsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type entrance_examsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $entrance_examsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "entrance_exams"
  objects: {
    exam_questions: Prisma.$exam_questionsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    year: number
    subject: string
    type: string
    description: string | null
    order: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["entrance_exams"]>
  composites: {}
}

export type entrance_examsGetPayload<S extends boolean | null | undefined | entrance_examsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload, S>

export type entrance_examsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<entrance_examsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Entrance_examsCountAggregateInputType | true
  }

export interface entrance_examsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['entrance_exams'], meta: { name: 'entrance_exams' } }
  /**
   * Find zero or one Entrance_exams that matches the filter.
   * @param {entrance_examsFindUniqueArgs} args - Arguments to find a Entrance_exams
   * @example
   * // Get one Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends entrance_examsFindUniqueArgs>(args: Prisma.SelectSubset<T, entrance_examsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Entrance_exams that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {entrance_examsFindUniqueOrThrowArgs} args - Arguments to find a Entrance_exams
   * @example
   * // Get one Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends entrance_examsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, entrance_examsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Entrance_exams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entrance_examsFindFirstArgs} args - Arguments to find a Entrance_exams
   * @example
   * // Get one Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends entrance_examsFindFirstArgs>(args?: Prisma.SelectSubset<T, entrance_examsFindFirstArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Entrance_exams that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entrance_examsFindFirstOrThrowArgs} args - Arguments to find a Entrance_exams
   * @example
   * // Get one Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends entrance_examsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, entrance_examsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Entrance_exams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entrance_examsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.findMany()
   * 
   * // Get first 10 Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const entrance_examsWithIdOnly = await prisma.entrance_exams.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends entrance_examsFindManyArgs>(args?: Prisma.SelectSubset<T, entrance_examsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Entrance_exams.
   * @param {entrance_examsCreateArgs} args - Arguments to create a Entrance_exams.
   * @example
   * // Create one Entrance_exams
   * const Entrance_exams = await prisma.entrance_exams.create({
   *   data: {
   *     // ... data to create a Entrance_exams
   *   }
   * })
   * 
   */
  create<T extends entrance_examsCreateArgs>(args: Prisma.SelectSubset<T, entrance_examsCreateArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Entrance_exams.
   * @param {entrance_examsCreateManyArgs} args - Arguments to create many Entrance_exams.
   * @example
   * // Create many Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends entrance_examsCreateManyArgs>(args?: Prisma.SelectSubset<T, entrance_examsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Entrance_exams and returns the data saved in the database.
   * @param {entrance_examsCreateManyAndReturnArgs} args - Arguments to create many Entrance_exams.
   * @example
   * // Create many Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Entrance_exams and only return the `id`
   * const entrance_examsWithIdOnly = await prisma.entrance_exams.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends entrance_examsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, entrance_examsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Entrance_exams.
   * @param {entrance_examsDeleteArgs} args - Arguments to delete one Entrance_exams.
   * @example
   * // Delete one Entrance_exams
   * const Entrance_exams = await prisma.entrance_exams.delete({
   *   where: {
   *     // ... filter to delete one Entrance_exams
   *   }
   * })
   * 
   */
  delete<T extends entrance_examsDeleteArgs>(args: Prisma.SelectSubset<T, entrance_examsDeleteArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Entrance_exams.
   * @param {entrance_examsUpdateArgs} args - Arguments to update one Entrance_exams.
   * @example
   * // Update one Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends entrance_examsUpdateArgs>(args: Prisma.SelectSubset<T, entrance_examsUpdateArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Entrance_exams.
   * @param {entrance_examsDeleteManyArgs} args - Arguments to filter Entrance_exams to delete.
   * @example
   * // Delete a few Entrance_exams
   * const { count } = await prisma.entrance_exams.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends entrance_examsDeleteManyArgs>(args?: Prisma.SelectSubset<T, entrance_examsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Entrance_exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entrance_examsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends entrance_examsUpdateManyArgs>(args: Prisma.SelectSubset<T, entrance_examsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Entrance_exams and returns the data updated in the database.
   * @param {entrance_examsUpdateManyAndReturnArgs} args - Arguments to update many Entrance_exams.
   * @example
   * // Update many Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Entrance_exams and only return the `id`
   * const entrance_examsWithIdOnly = await prisma.entrance_exams.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends entrance_examsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, entrance_examsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Entrance_exams.
   * @param {entrance_examsUpsertArgs} args - Arguments to update or create a Entrance_exams.
   * @example
   * // Update or create a Entrance_exams
   * const entrance_exams = await prisma.entrance_exams.upsert({
   *   create: {
   *     // ... data to create a Entrance_exams
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Entrance_exams we want to update
   *   }
   * })
   */
  upsert<T extends entrance_examsUpsertArgs>(args: Prisma.SelectSubset<T, entrance_examsUpsertArgs<ExtArgs>>): Prisma.Prisma__entrance_examsClient<runtime.Types.Result.GetResult<Prisma.$entrance_examsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Entrance_exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entrance_examsCountArgs} args - Arguments to filter Entrance_exams to count.
   * @example
   * // Count the number of Entrance_exams
   * const count = await prisma.entrance_exams.count({
   *   where: {
   *     // ... the filter for the Entrance_exams we want to count
   *   }
   * })
  **/
  count<T extends entrance_examsCountArgs>(
    args?: Prisma.Subset<T, entrance_examsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Entrance_examsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Entrance_exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Entrance_examsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Entrance_examsAggregateArgs>(args: Prisma.Subset<T, Entrance_examsAggregateArgs>): Prisma.PrismaPromise<GetEntrance_examsAggregateType<T>>

  /**
   * Group by Entrance_exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {entrance_examsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends entrance_examsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: entrance_examsGroupByArgs['orderBy'] }
      : { orderBy?: entrance_examsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, entrance_examsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEntrance_examsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the entrance_exams model
 */
readonly fields: entrance_examsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for entrance_exams.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__entrance_examsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  exam_questions<T extends Prisma.entrance_exams$exam_questionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.entrance_exams$exam_questionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$exam_questionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the entrance_exams model
 */
export interface entrance_examsFieldRefs {
  readonly id: Prisma.FieldRef<"entrance_exams", 'String'>
  readonly title: Prisma.FieldRef<"entrance_exams", 'String'>
  readonly year: Prisma.FieldRef<"entrance_exams", 'Int'>
  readonly subject: Prisma.FieldRef<"entrance_exams", 'String'>
  readonly type: Prisma.FieldRef<"entrance_exams", 'String'>
  readonly description: Prisma.FieldRef<"entrance_exams", 'String'>
  readonly order: Prisma.FieldRef<"entrance_exams", 'Int'>
  readonly createdAt: Prisma.FieldRef<"entrance_exams", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"entrance_exams", 'DateTime'>
}
    

// Custom InputTypes
/**
 * entrance_exams findUnique
 */
export type entrance_examsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * Filter, which entrance_exams to fetch.
   */
  where: Prisma.entrance_examsWhereUniqueInput
}

/**
 * entrance_exams findUniqueOrThrow
 */
export type entrance_examsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * Filter, which entrance_exams to fetch.
   */
  where: Prisma.entrance_examsWhereUniqueInput
}

/**
 * entrance_exams findFirst
 */
export type entrance_examsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * Filter, which entrance_exams to fetch.
   */
  where?: Prisma.entrance_examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entrance_exams to fetch.
   */
  orderBy?: Prisma.entrance_examsOrderByWithRelationInput | Prisma.entrance_examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for entrance_exams.
   */
  cursor?: Prisma.entrance_examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entrance_exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entrance_exams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of entrance_exams.
   */
  distinct?: Prisma.Entrance_examsScalarFieldEnum | Prisma.Entrance_examsScalarFieldEnum[]
}

/**
 * entrance_exams findFirstOrThrow
 */
export type entrance_examsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * Filter, which entrance_exams to fetch.
   */
  where?: Prisma.entrance_examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entrance_exams to fetch.
   */
  orderBy?: Prisma.entrance_examsOrderByWithRelationInput | Prisma.entrance_examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for entrance_exams.
   */
  cursor?: Prisma.entrance_examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entrance_exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entrance_exams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of entrance_exams.
   */
  distinct?: Prisma.Entrance_examsScalarFieldEnum | Prisma.Entrance_examsScalarFieldEnum[]
}

/**
 * entrance_exams findMany
 */
export type entrance_examsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * Filter, which entrance_exams to fetch.
   */
  where?: Prisma.entrance_examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of entrance_exams to fetch.
   */
  orderBy?: Prisma.entrance_examsOrderByWithRelationInput | Prisma.entrance_examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing entrance_exams.
   */
  cursor?: Prisma.entrance_examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` entrance_exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` entrance_exams.
   */
  skip?: number
  distinct?: Prisma.Entrance_examsScalarFieldEnum | Prisma.Entrance_examsScalarFieldEnum[]
}

/**
 * entrance_exams create
 */
export type entrance_examsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * The data needed to create a entrance_exams.
   */
  data: Prisma.XOR<Prisma.entrance_examsCreateInput, Prisma.entrance_examsUncheckedCreateInput>
}

/**
 * entrance_exams createMany
 */
export type entrance_examsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many entrance_exams.
   */
  data: Prisma.entrance_examsCreateManyInput | Prisma.entrance_examsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * entrance_exams createManyAndReturn
 */
export type entrance_examsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * The data used to create many entrance_exams.
   */
  data: Prisma.entrance_examsCreateManyInput | Prisma.entrance_examsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * entrance_exams update
 */
export type entrance_examsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * The data needed to update a entrance_exams.
   */
  data: Prisma.XOR<Prisma.entrance_examsUpdateInput, Prisma.entrance_examsUncheckedUpdateInput>
  /**
   * Choose, which entrance_exams to update.
   */
  where: Prisma.entrance_examsWhereUniqueInput
}

/**
 * entrance_exams updateMany
 */
export type entrance_examsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update entrance_exams.
   */
  data: Prisma.XOR<Prisma.entrance_examsUpdateManyMutationInput, Prisma.entrance_examsUncheckedUpdateManyInput>
  /**
   * Filter which entrance_exams to update
   */
  where?: Prisma.entrance_examsWhereInput
  /**
   * Limit how many entrance_exams to update.
   */
  limit?: number
}

/**
 * entrance_exams updateManyAndReturn
 */
export type entrance_examsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * The data used to update entrance_exams.
   */
  data: Prisma.XOR<Prisma.entrance_examsUpdateManyMutationInput, Prisma.entrance_examsUncheckedUpdateManyInput>
  /**
   * Filter which entrance_exams to update
   */
  where?: Prisma.entrance_examsWhereInput
  /**
   * Limit how many entrance_exams to update.
   */
  limit?: number
}

/**
 * entrance_exams upsert
 */
export type entrance_examsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * The filter to search for the entrance_exams to update in case it exists.
   */
  where: Prisma.entrance_examsWhereUniqueInput
  /**
   * In case the entrance_exams found by the `where` argument doesn't exist, create a new entrance_exams with this data.
   */
  create: Prisma.XOR<Prisma.entrance_examsCreateInput, Prisma.entrance_examsUncheckedCreateInput>
  /**
   * In case the entrance_exams was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.entrance_examsUpdateInput, Prisma.entrance_examsUncheckedUpdateInput>
}

/**
 * entrance_exams delete
 */
export type entrance_examsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
  /**
   * Filter which entrance_exams to delete.
   */
  where: Prisma.entrance_examsWhereUniqueInput
}

/**
 * entrance_exams deleteMany
 */
export type entrance_examsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which entrance_exams to delete
   */
  where?: Prisma.entrance_examsWhereInput
  /**
   * Limit how many entrance_exams to delete.
   */
  limit?: number
}

/**
 * entrance_exams.exam_questions
 */
export type entrance_exams$exam_questionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exam_questions
   */
  select?: Prisma.exam_questionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exam_questions
   */
  omit?: Prisma.exam_questionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.exam_questionsInclude<ExtArgs> | null
  where?: Prisma.exam_questionsWhereInput
  orderBy?: Prisma.exam_questionsOrderByWithRelationInput | Prisma.exam_questionsOrderByWithRelationInput[]
  cursor?: Prisma.exam_questionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Exam_questionsScalarFieldEnum | Prisma.Exam_questionsScalarFieldEnum[]
}

/**
 * entrance_exams without action
 */
export type entrance_examsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the entrance_exams
   */
  select?: Prisma.entrance_examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the entrance_exams
   */
  omit?: Prisma.entrance_examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.entrance_examsInclude<ExtArgs> | null
}
