
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `exams` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model exams
 * 
 */
export type examsModel = runtime.Types.Result.DefaultSelection<Prisma.$examsPayload>

export type AggregateExams = {
  _count: ExamsCountAggregateOutputType | null
  _avg: ExamsAvgAggregateOutputType | null
  _sum: ExamsSumAggregateOutputType | null
  _min: ExamsMinAggregateOutputType | null
  _max: ExamsMaxAggregateOutputType | null
}

export type ExamsAvgAggregateOutputType = {
  duration: number | null
  order: number | null
}

export type ExamsSumAggregateOutputType = {
  duration: number | null
  order: number | null
}

export type ExamsMinAggregateOutputType = {
  id: string | null
  videoId: string | null
  duration: number | null
  order: number | null
  chapterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ExamsMaxAggregateOutputType = {
  id: string | null
  videoId: string | null
  duration: number | null
  order: number | null
  chapterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ExamsCountAggregateOutputType = {
  id: number
  videoId: number
  duration: number
  order: number
  chapterId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ExamsAvgAggregateInputType = {
  duration?: true
  order?: true
}

export type ExamsSumAggregateInputType = {
  duration?: true
  order?: true
}

export type ExamsMinAggregateInputType = {
  id?: true
  videoId?: true
  duration?: true
  order?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
}

export type ExamsMaxAggregateInputType = {
  id?: true
  videoId?: true
  duration?: true
  order?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
}

export type ExamsCountAggregateInputType = {
  id?: true
  videoId?: true
  duration?: true
  order?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ExamsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which exams to aggregate.
   */
  where?: Prisma.examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of exams to fetch.
   */
  orderBy?: Prisma.examsOrderByWithRelationInput | Prisma.examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` exams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned exams
  **/
  _count?: true | ExamsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExamsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExamsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExamsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExamsMaxAggregateInputType
}

export type GetExamsAggregateType<T extends ExamsAggregateArgs> = {
      [P in keyof T & keyof AggregateExams]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExams[P]>
    : Prisma.GetScalarType<T[P], AggregateExams[P]>
}




export type examsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.examsWhereInput
  orderBy?: Prisma.examsOrderByWithAggregationInput | Prisma.examsOrderByWithAggregationInput[]
  by: Prisma.ExamsScalarFieldEnum[] | Prisma.ExamsScalarFieldEnum
  having?: Prisma.examsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExamsCountAggregateInputType | true
  _avg?: ExamsAvgAggregateInputType
  _sum?: ExamsSumAggregateInputType
  _min?: ExamsMinAggregateInputType
  _max?: ExamsMaxAggregateInputType
}

export type ExamsGroupByOutputType = {
  id: string
  videoId: string
  duration: number
  order: number
  chapterId: string
  createdAt: Date
  updatedAt: Date
  _count: ExamsCountAggregateOutputType | null
  _avg: ExamsAvgAggregateOutputType | null
  _sum: ExamsSumAggregateOutputType | null
  _min: ExamsMinAggregateOutputType | null
  _max: ExamsMaxAggregateOutputType | null
}

type GetExamsGroupByPayload<T extends examsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExamsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExamsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExamsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExamsGroupByOutputType[P]>
      }
    >
  > 



export type examsWhereInput = {
  AND?: Prisma.examsWhereInput | Prisma.examsWhereInput[]
  OR?: Prisma.examsWhereInput[]
  NOT?: Prisma.examsWhereInput | Prisma.examsWhereInput[]
  id?: Prisma.StringFilter<"exams"> | string
  videoId?: Prisma.StringFilter<"exams"> | string
  duration?: Prisma.IntFilter<"exams"> | number
  order?: Prisma.IntFilter<"exams"> | number
  chapterId?: Prisma.StringFilter<"exams"> | string
  createdAt?: Prisma.DateTimeFilter<"exams"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"exams"> | Date | string
  chapters?: Prisma.XOR<Prisma.ChaptersScalarRelationFilter, Prisma.chaptersWhereInput>
}

export type examsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  chapters?: Prisma.chaptersOrderByWithRelationInput
}

export type examsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.examsWhereInput | Prisma.examsWhereInput[]
  OR?: Prisma.examsWhereInput[]
  NOT?: Prisma.examsWhereInput | Prisma.examsWhereInput[]
  videoId?: Prisma.StringFilter<"exams"> | string
  duration?: Prisma.IntFilter<"exams"> | number
  order?: Prisma.IntFilter<"exams"> | number
  chapterId?: Prisma.StringFilter<"exams"> | string
  createdAt?: Prisma.DateTimeFilter<"exams"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"exams"> | Date | string
  chapters?: Prisma.XOR<Prisma.ChaptersScalarRelationFilter, Prisma.chaptersWhereInput>
}, "id">

export type examsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.examsCountOrderByAggregateInput
  _avg?: Prisma.examsAvgOrderByAggregateInput
  _max?: Prisma.examsMaxOrderByAggregateInput
  _min?: Prisma.examsMinOrderByAggregateInput
  _sum?: Prisma.examsSumOrderByAggregateInput
}

export type examsScalarWhereWithAggregatesInput = {
  AND?: Prisma.examsScalarWhereWithAggregatesInput | Prisma.examsScalarWhereWithAggregatesInput[]
  OR?: Prisma.examsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.examsScalarWhereWithAggregatesInput | Prisma.examsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"exams"> | string
  videoId?: Prisma.StringWithAggregatesFilter<"exams"> | string
  duration?: Prisma.IntWithAggregatesFilter<"exams"> | number
  order?: Prisma.IntWithAggregatesFilter<"exams"> | number
  chapterId?: Prisma.StringWithAggregatesFilter<"exams"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"exams"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"exams"> | Date | string
}

export type examsCreateInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
  chapters: Prisma.chaptersCreateNestedOneWithoutExamsInput
}

export type examsUncheckedCreateInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  chapterId: string
  createdAt?: Date | string
  updatedAt: Date | string
}

export type examsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapters?: Prisma.chaptersUpdateOneRequiredWithoutExamsNestedInput
}

export type examsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type examsCreateManyInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  chapterId: string
  createdAt?: Date | string
  updatedAt: Date | string
}

export type examsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type examsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ExamsListRelationFilter = {
  every?: Prisma.examsWhereInput
  some?: Prisma.examsWhereInput
  none?: Prisma.examsWhereInput
}

export type examsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type examsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type examsAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type examsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type examsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type examsSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type examsCreateNestedManyWithoutChaptersInput = {
  create?: Prisma.XOR<Prisma.examsCreateWithoutChaptersInput, Prisma.examsUncheckedCreateWithoutChaptersInput> | Prisma.examsCreateWithoutChaptersInput[] | Prisma.examsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.examsCreateOrConnectWithoutChaptersInput | Prisma.examsCreateOrConnectWithoutChaptersInput[]
  createMany?: Prisma.examsCreateManyChaptersInputEnvelope
  connect?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
}

export type examsUncheckedCreateNestedManyWithoutChaptersInput = {
  create?: Prisma.XOR<Prisma.examsCreateWithoutChaptersInput, Prisma.examsUncheckedCreateWithoutChaptersInput> | Prisma.examsCreateWithoutChaptersInput[] | Prisma.examsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.examsCreateOrConnectWithoutChaptersInput | Prisma.examsCreateOrConnectWithoutChaptersInput[]
  createMany?: Prisma.examsCreateManyChaptersInputEnvelope
  connect?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
}

export type examsUpdateManyWithoutChaptersNestedInput = {
  create?: Prisma.XOR<Prisma.examsCreateWithoutChaptersInput, Prisma.examsUncheckedCreateWithoutChaptersInput> | Prisma.examsCreateWithoutChaptersInput[] | Prisma.examsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.examsCreateOrConnectWithoutChaptersInput | Prisma.examsCreateOrConnectWithoutChaptersInput[]
  upsert?: Prisma.examsUpsertWithWhereUniqueWithoutChaptersInput | Prisma.examsUpsertWithWhereUniqueWithoutChaptersInput[]
  createMany?: Prisma.examsCreateManyChaptersInputEnvelope
  set?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  disconnect?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  delete?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  connect?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  update?: Prisma.examsUpdateWithWhereUniqueWithoutChaptersInput | Prisma.examsUpdateWithWhereUniqueWithoutChaptersInput[]
  updateMany?: Prisma.examsUpdateManyWithWhereWithoutChaptersInput | Prisma.examsUpdateManyWithWhereWithoutChaptersInput[]
  deleteMany?: Prisma.examsScalarWhereInput | Prisma.examsScalarWhereInput[]
}

export type examsUncheckedUpdateManyWithoutChaptersNestedInput = {
  create?: Prisma.XOR<Prisma.examsCreateWithoutChaptersInput, Prisma.examsUncheckedCreateWithoutChaptersInput> | Prisma.examsCreateWithoutChaptersInput[] | Prisma.examsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.examsCreateOrConnectWithoutChaptersInput | Prisma.examsCreateOrConnectWithoutChaptersInput[]
  upsert?: Prisma.examsUpsertWithWhereUniqueWithoutChaptersInput | Prisma.examsUpsertWithWhereUniqueWithoutChaptersInput[]
  createMany?: Prisma.examsCreateManyChaptersInputEnvelope
  set?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  disconnect?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  delete?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  connect?: Prisma.examsWhereUniqueInput | Prisma.examsWhereUniqueInput[]
  update?: Prisma.examsUpdateWithWhereUniqueWithoutChaptersInput | Prisma.examsUpdateWithWhereUniqueWithoutChaptersInput[]
  updateMany?: Prisma.examsUpdateManyWithWhereWithoutChaptersInput | Prisma.examsUpdateManyWithWhereWithoutChaptersInput[]
  deleteMany?: Prisma.examsScalarWhereInput | Prisma.examsScalarWhereInput[]
}

export type examsCreateWithoutChaptersInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type examsUncheckedCreateWithoutChaptersInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type examsCreateOrConnectWithoutChaptersInput = {
  where: Prisma.examsWhereUniqueInput
  create: Prisma.XOR<Prisma.examsCreateWithoutChaptersInput, Prisma.examsUncheckedCreateWithoutChaptersInput>
}

export type examsCreateManyChaptersInputEnvelope = {
  data: Prisma.examsCreateManyChaptersInput | Prisma.examsCreateManyChaptersInput[]
  skipDuplicates?: boolean
}

export type examsUpsertWithWhereUniqueWithoutChaptersInput = {
  where: Prisma.examsWhereUniqueInput
  update: Prisma.XOR<Prisma.examsUpdateWithoutChaptersInput, Prisma.examsUncheckedUpdateWithoutChaptersInput>
  create: Prisma.XOR<Prisma.examsCreateWithoutChaptersInput, Prisma.examsUncheckedCreateWithoutChaptersInput>
}

export type examsUpdateWithWhereUniqueWithoutChaptersInput = {
  where: Prisma.examsWhereUniqueInput
  data: Prisma.XOR<Prisma.examsUpdateWithoutChaptersInput, Prisma.examsUncheckedUpdateWithoutChaptersInput>
}

export type examsUpdateManyWithWhereWithoutChaptersInput = {
  where: Prisma.examsScalarWhereInput
  data: Prisma.XOR<Prisma.examsUpdateManyMutationInput, Prisma.examsUncheckedUpdateManyWithoutChaptersInput>
}

export type examsScalarWhereInput = {
  AND?: Prisma.examsScalarWhereInput | Prisma.examsScalarWhereInput[]
  OR?: Prisma.examsScalarWhereInput[]
  NOT?: Prisma.examsScalarWhereInput | Prisma.examsScalarWhereInput[]
  id?: Prisma.StringFilter<"exams"> | string
  videoId?: Prisma.StringFilter<"exams"> | string
  duration?: Prisma.IntFilter<"exams"> | number
  order?: Prisma.IntFilter<"exams"> | number
  chapterId?: Prisma.StringFilter<"exams"> | string
  createdAt?: Prisma.DateTimeFilter<"exams"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"exams"> | Date | string
}

export type examsCreateManyChaptersInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type examsUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type examsUncheckedUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type examsUncheckedUpdateManyWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type examsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exams"]>

export type examsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exams"]>

export type examsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exams"]>

export type examsSelectScalar = {
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type examsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "videoId" | "duration" | "order" | "chapterId" | "createdAt" | "updatedAt", ExtArgs["result"]["exams"]>
export type examsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}
export type examsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}
export type examsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}

export type $examsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "exams"
  objects: {
    chapters: Prisma.$chaptersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    videoId: string
    duration: number
    order: number
    chapterId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["exams"]>
  composites: {}
}

export type examsGetPayload<S extends boolean | null | undefined | examsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$examsPayload, S>

export type examsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<examsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExamsCountAggregateInputType | true
  }

export interface examsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['exams'], meta: { name: 'exams' } }
  /**
   * Find zero or one Exams that matches the filter.
   * @param {examsFindUniqueArgs} args - Arguments to find a Exams
   * @example
   * // Get one Exams
   * const exams = await prisma.exams.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends examsFindUniqueArgs>(args: Prisma.SelectSubset<T, examsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Exams that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {examsFindUniqueOrThrowArgs} args - Arguments to find a Exams
   * @example
   * // Get one Exams
   * const exams = await prisma.exams.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends examsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, examsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Exams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {examsFindFirstArgs} args - Arguments to find a Exams
   * @example
   * // Get one Exams
   * const exams = await prisma.exams.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends examsFindFirstArgs>(args?: Prisma.SelectSubset<T, examsFindFirstArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Exams that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {examsFindFirstOrThrowArgs} args - Arguments to find a Exams
   * @example
   * // Get one Exams
   * const exams = await prisma.exams.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends examsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, examsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Exams that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {examsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Exams
   * const exams = await prisma.exams.findMany()
   * 
   * // Get first 10 Exams
   * const exams = await prisma.exams.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const examsWithIdOnly = await prisma.exams.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends examsFindManyArgs>(args?: Prisma.SelectSubset<T, examsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Exams.
   * @param {examsCreateArgs} args - Arguments to create a Exams.
   * @example
   * // Create one Exams
   * const Exams = await prisma.exams.create({
   *   data: {
   *     // ... data to create a Exams
   *   }
   * })
   * 
   */
  create<T extends examsCreateArgs>(args: Prisma.SelectSubset<T, examsCreateArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Exams.
   * @param {examsCreateManyArgs} args - Arguments to create many Exams.
   * @example
   * // Create many Exams
   * const exams = await prisma.exams.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends examsCreateManyArgs>(args?: Prisma.SelectSubset<T, examsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Exams and returns the data saved in the database.
   * @param {examsCreateManyAndReturnArgs} args - Arguments to create many Exams.
   * @example
   * // Create many Exams
   * const exams = await prisma.exams.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Exams and only return the `id`
   * const examsWithIdOnly = await prisma.exams.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends examsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, examsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Exams.
   * @param {examsDeleteArgs} args - Arguments to delete one Exams.
   * @example
   * // Delete one Exams
   * const Exams = await prisma.exams.delete({
   *   where: {
   *     // ... filter to delete one Exams
   *   }
   * })
   * 
   */
  delete<T extends examsDeleteArgs>(args: Prisma.SelectSubset<T, examsDeleteArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Exams.
   * @param {examsUpdateArgs} args - Arguments to update one Exams.
   * @example
   * // Update one Exams
   * const exams = await prisma.exams.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends examsUpdateArgs>(args: Prisma.SelectSubset<T, examsUpdateArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Exams.
   * @param {examsDeleteManyArgs} args - Arguments to filter Exams to delete.
   * @example
   * // Delete a few Exams
   * const { count } = await prisma.exams.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends examsDeleteManyArgs>(args?: Prisma.SelectSubset<T, examsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {examsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Exams
   * const exams = await prisma.exams.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends examsUpdateManyArgs>(args: Prisma.SelectSubset<T, examsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Exams and returns the data updated in the database.
   * @param {examsUpdateManyAndReturnArgs} args - Arguments to update many Exams.
   * @example
   * // Update many Exams
   * const exams = await prisma.exams.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Exams and only return the `id`
   * const examsWithIdOnly = await prisma.exams.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends examsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, examsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Exams.
   * @param {examsUpsertArgs} args - Arguments to update or create a Exams.
   * @example
   * // Update or create a Exams
   * const exams = await prisma.exams.upsert({
   *   create: {
   *     // ... data to create a Exams
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Exams we want to update
   *   }
   * })
   */
  upsert<T extends examsUpsertArgs>(args: Prisma.SelectSubset<T, examsUpsertArgs<ExtArgs>>): Prisma.Prisma__examsClient<runtime.Types.Result.GetResult<Prisma.$examsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {examsCountArgs} args - Arguments to filter Exams to count.
   * @example
   * // Count the number of Exams
   * const count = await prisma.exams.count({
   *   where: {
   *     // ... the filter for the Exams we want to count
   *   }
   * })
  **/
  count<T extends examsCountArgs>(
    args?: Prisma.Subset<T, examsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExamsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExamsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExamsAggregateArgs>(args: Prisma.Subset<T, ExamsAggregateArgs>): Prisma.PrismaPromise<GetExamsAggregateType<T>>

  /**
   * Group by Exams.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {examsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends examsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: examsGroupByArgs['orderBy'] }
      : { orderBy?: examsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, examsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExamsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the exams model
 */
readonly fields: examsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for exams.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__examsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chapters<T extends Prisma.chaptersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.chaptersDefaultArgs<ExtArgs>>): Prisma.Prisma__chaptersClient<runtime.Types.Result.GetResult<Prisma.$chaptersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the exams model
 */
export interface examsFieldRefs {
  readonly id: Prisma.FieldRef<"exams", 'String'>
  readonly videoId: Prisma.FieldRef<"exams", 'String'>
  readonly duration: Prisma.FieldRef<"exams", 'Int'>
  readonly order: Prisma.FieldRef<"exams", 'Int'>
  readonly chapterId: Prisma.FieldRef<"exams", 'String'>
  readonly createdAt: Prisma.FieldRef<"exams", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"exams", 'DateTime'>
}
    

// Custom InputTypes
/**
 * exams findUnique
 */
export type examsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * Filter, which exams to fetch.
   */
  where: Prisma.examsWhereUniqueInput
}

/**
 * exams findUniqueOrThrow
 */
export type examsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * Filter, which exams to fetch.
   */
  where: Prisma.examsWhereUniqueInput
}

/**
 * exams findFirst
 */
export type examsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * Filter, which exams to fetch.
   */
  where?: Prisma.examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of exams to fetch.
   */
  orderBy?: Prisma.examsOrderByWithRelationInput | Prisma.examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for exams.
   */
  cursor?: Prisma.examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` exams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of exams.
   */
  distinct?: Prisma.ExamsScalarFieldEnum | Prisma.ExamsScalarFieldEnum[]
}

/**
 * exams findFirstOrThrow
 */
export type examsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * Filter, which exams to fetch.
   */
  where?: Prisma.examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of exams to fetch.
   */
  orderBy?: Prisma.examsOrderByWithRelationInput | Prisma.examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for exams.
   */
  cursor?: Prisma.examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` exams.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of exams.
   */
  distinct?: Prisma.ExamsScalarFieldEnum | Prisma.ExamsScalarFieldEnum[]
}

/**
 * exams findMany
 */
export type examsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * Filter, which exams to fetch.
   */
  where?: Prisma.examsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of exams to fetch.
   */
  orderBy?: Prisma.examsOrderByWithRelationInput | Prisma.examsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing exams.
   */
  cursor?: Prisma.examsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` exams from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` exams.
   */
  skip?: number
  distinct?: Prisma.ExamsScalarFieldEnum | Prisma.ExamsScalarFieldEnum[]
}

/**
 * exams create
 */
export type examsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * The data needed to create a exams.
   */
  data: Prisma.XOR<Prisma.examsCreateInput, Prisma.examsUncheckedCreateInput>
}

/**
 * exams createMany
 */
export type examsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many exams.
   */
  data: Prisma.examsCreateManyInput | Prisma.examsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * exams createManyAndReturn
 */
export type examsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * The data used to create many exams.
   */
  data: Prisma.examsCreateManyInput | Prisma.examsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * exams update
 */
export type examsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * The data needed to update a exams.
   */
  data: Prisma.XOR<Prisma.examsUpdateInput, Prisma.examsUncheckedUpdateInput>
  /**
   * Choose, which exams to update.
   */
  where: Prisma.examsWhereUniqueInput
}

/**
 * exams updateMany
 */
export type examsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update exams.
   */
  data: Prisma.XOR<Prisma.examsUpdateManyMutationInput, Prisma.examsUncheckedUpdateManyInput>
  /**
   * Filter which exams to update
   */
  where?: Prisma.examsWhereInput
  /**
   * Limit how many exams to update.
   */
  limit?: number
}

/**
 * exams updateManyAndReturn
 */
export type examsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * The data used to update exams.
   */
  data: Prisma.XOR<Prisma.examsUpdateManyMutationInput, Prisma.examsUncheckedUpdateManyInput>
  /**
   * Filter which exams to update
   */
  where?: Prisma.examsWhereInput
  /**
   * Limit how many exams to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * exams upsert
 */
export type examsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * The filter to search for the exams to update in case it exists.
   */
  where: Prisma.examsWhereUniqueInput
  /**
   * In case the exams found by the `where` argument doesn't exist, create a new exams with this data.
   */
  create: Prisma.XOR<Prisma.examsCreateInput, Prisma.examsUncheckedCreateInput>
  /**
   * In case the exams was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.examsUpdateInput, Prisma.examsUncheckedUpdateInput>
}

/**
 * exams delete
 */
export type examsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
  /**
   * Filter which exams to delete.
   */
  where: Prisma.examsWhereUniqueInput
}

/**
 * exams deleteMany
 */
export type examsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which exams to delete
   */
  where?: Prisma.examsWhereInput
  /**
   * Limit how many exams to delete.
   */
  limit?: number
}

/**
 * exams without action
 */
export type examsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the exams
   */
  select?: Prisma.examsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the exams
   */
  omit?: Prisma.examsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.examsInclude<ExtArgs> | null
}
