
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `teachings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model teachings
 * 
 */
export type teachingsModel = runtime.Types.Result.DefaultSelection<Prisma.$teachingsPayload>

export type AggregateTeachings = {
  _count: TeachingsCountAggregateOutputType | null
  _avg: TeachingsAvgAggregateOutputType | null
  _sum: TeachingsSumAggregateOutputType | null
  _min: TeachingsMinAggregateOutputType | null
  _max: TeachingsMaxAggregateOutputType | null
}

export type TeachingsAvgAggregateOutputType = {
  duration: number | null
  order: number | null
}

export type TeachingsSumAggregateOutputType = {
  duration: number | null
  order: number | null
}

export type TeachingsMinAggregateOutputType = {
  id: string | null
  videoId: string | null
  duration: number | null
  order: number | null
  chapterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TeachingsMaxAggregateOutputType = {
  id: string | null
  videoId: string | null
  duration: number | null
  order: number | null
  chapterId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TeachingsCountAggregateOutputType = {
  id: number
  videoId: number
  duration: number
  order: number
  chapterId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TeachingsAvgAggregateInputType = {
  duration?: true
  order?: true
}

export type TeachingsSumAggregateInputType = {
  duration?: true
  order?: true
}

export type TeachingsMinAggregateInputType = {
  id?: true
  videoId?: true
  duration?: true
  order?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
}

export type TeachingsMaxAggregateInputType = {
  id?: true
  videoId?: true
  duration?: true
  order?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
}

export type TeachingsCountAggregateInputType = {
  id?: true
  videoId?: true
  duration?: true
  order?: true
  chapterId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TeachingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which teachings to aggregate.
   */
  where?: Prisma.teachingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of teachings to fetch.
   */
  orderBy?: Prisma.teachingsOrderByWithRelationInput | Prisma.teachingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.teachingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` teachings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` teachings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned teachings
  **/
  _count?: true | TeachingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TeachingsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TeachingsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TeachingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TeachingsMaxAggregateInputType
}

export type GetTeachingsAggregateType<T extends TeachingsAggregateArgs> = {
      [P in keyof T & keyof AggregateTeachings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTeachings[P]>
    : Prisma.GetScalarType<T[P], AggregateTeachings[P]>
}




export type teachingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.teachingsWhereInput
  orderBy?: Prisma.teachingsOrderByWithAggregationInput | Prisma.teachingsOrderByWithAggregationInput[]
  by: Prisma.TeachingsScalarFieldEnum[] | Prisma.TeachingsScalarFieldEnum
  having?: Prisma.teachingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TeachingsCountAggregateInputType | true
  _avg?: TeachingsAvgAggregateInputType
  _sum?: TeachingsSumAggregateInputType
  _min?: TeachingsMinAggregateInputType
  _max?: TeachingsMaxAggregateInputType
}

export type TeachingsGroupByOutputType = {
  id: string
  videoId: string
  duration: number
  order: number
  chapterId: string
  createdAt: Date
  updatedAt: Date
  _count: TeachingsCountAggregateOutputType | null
  _avg: TeachingsAvgAggregateOutputType | null
  _sum: TeachingsSumAggregateOutputType | null
  _min: TeachingsMinAggregateOutputType | null
  _max: TeachingsMaxAggregateOutputType | null
}

type GetTeachingsGroupByPayload<T extends teachingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TeachingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TeachingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TeachingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TeachingsGroupByOutputType[P]>
      }
    >
  > 



export type teachingsWhereInput = {
  AND?: Prisma.teachingsWhereInput | Prisma.teachingsWhereInput[]
  OR?: Prisma.teachingsWhereInput[]
  NOT?: Prisma.teachingsWhereInput | Prisma.teachingsWhereInput[]
  id?: Prisma.StringFilter<"teachings"> | string
  videoId?: Prisma.StringFilter<"teachings"> | string
  duration?: Prisma.IntFilter<"teachings"> | number
  order?: Prisma.IntFilter<"teachings"> | number
  chapterId?: Prisma.StringFilter<"teachings"> | string
  createdAt?: Prisma.DateTimeFilter<"teachings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"teachings"> | Date | string
  chapters?: Prisma.XOR<Prisma.ChaptersScalarRelationFilter, Prisma.chaptersWhereInput>
}

export type teachingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  chapters?: Prisma.chaptersOrderByWithRelationInput
}

export type teachingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.teachingsWhereInput | Prisma.teachingsWhereInput[]
  OR?: Prisma.teachingsWhereInput[]
  NOT?: Prisma.teachingsWhereInput | Prisma.teachingsWhereInput[]
  videoId?: Prisma.StringFilter<"teachings"> | string
  duration?: Prisma.IntFilter<"teachings"> | number
  order?: Prisma.IntFilter<"teachings"> | number
  chapterId?: Prisma.StringFilter<"teachings"> | string
  createdAt?: Prisma.DateTimeFilter<"teachings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"teachings"> | Date | string
  chapters?: Prisma.XOR<Prisma.ChaptersScalarRelationFilter, Prisma.chaptersWhereInput>
}, "id">

export type teachingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.teachingsCountOrderByAggregateInput
  _avg?: Prisma.teachingsAvgOrderByAggregateInput
  _max?: Prisma.teachingsMaxOrderByAggregateInput
  _min?: Prisma.teachingsMinOrderByAggregateInput
  _sum?: Prisma.teachingsSumOrderByAggregateInput
}

export type teachingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.teachingsScalarWhereWithAggregatesInput | Prisma.teachingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.teachingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.teachingsScalarWhereWithAggregatesInput | Prisma.teachingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"teachings"> | string
  videoId?: Prisma.StringWithAggregatesFilter<"teachings"> | string
  duration?: Prisma.IntWithAggregatesFilter<"teachings"> | number
  order?: Prisma.IntWithAggregatesFilter<"teachings"> | number
  chapterId?: Prisma.StringWithAggregatesFilter<"teachings"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"teachings"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"teachings"> | Date | string
}

export type teachingsCreateInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
  chapters: Prisma.chaptersCreateNestedOneWithoutTeachingsInput
}

export type teachingsUncheckedCreateInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  chapterId: string
  createdAt?: Date | string
  updatedAt: Date | string
}

export type teachingsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chapters?: Prisma.chaptersUpdateOneRequiredWithoutTeachingsNestedInput
}

export type teachingsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type teachingsCreateManyInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  chapterId: string
  createdAt?: Date | string
  updatedAt: Date | string
}

export type teachingsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type teachingsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeachingsListRelationFilter = {
  every?: Prisma.teachingsWhereInput
  some?: Prisma.teachingsWhereInput
  none?: Prisma.teachingsWhereInput
}

export type teachingsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type teachingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type teachingsAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type teachingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type teachingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type teachingsSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type teachingsCreateNestedManyWithoutChaptersInput = {
  create?: Prisma.XOR<Prisma.teachingsCreateWithoutChaptersInput, Prisma.teachingsUncheckedCreateWithoutChaptersInput> | Prisma.teachingsCreateWithoutChaptersInput[] | Prisma.teachingsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.teachingsCreateOrConnectWithoutChaptersInput | Prisma.teachingsCreateOrConnectWithoutChaptersInput[]
  createMany?: Prisma.teachingsCreateManyChaptersInputEnvelope
  connect?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
}

export type teachingsUncheckedCreateNestedManyWithoutChaptersInput = {
  create?: Prisma.XOR<Prisma.teachingsCreateWithoutChaptersInput, Prisma.teachingsUncheckedCreateWithoutChaptersInput> | Prisma.teachingsCreateWithoutChaptersInput[] | Prisma.teachingsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.teachingsCreateOrConnectWithoutChaptersInput | Prisma.teachingsCreateOrConnectWithoutChaptersInput[]
  createMany?: Prisma.teachingsCreateManyChaptersInputEnvelope
  connect?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
}

export type teachingsUpdateManyWithoutChaptersNestedInput = {
  create?: Prisma.XOR<Prisma.teachingsCreateWithoutChaptersInput, Prisma.teachingsUncheckedCreateWithoutChaptersInput> | Prisma.teachingsCreateWithoutChaptersInput[] | Prisma.teachingsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.teachingsCreateOrConnectWithoutChaptersInput | Prisma.teachingsCreateOrConnectWithoutChaptersInput[]
  upsert?: Prisma.teachingsUpsertWithWhereUniqueWithoutChaptersInput | Prisma.teachingsUpsertWithWhereUniqueWithoutChaptersInput[]
  createMany?: Prisma.teachingsCreateManyChaptersInputEnvelope
  set?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  disconnect?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  delete?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  connect?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  update?: Prisma.teachingsUpdateWithWhereUniqueWithoutChaptersInput | Prisma.teachingsUpdateWithWhereUniqueWithoutChaptersInput[]
  updateMany?: Prisma.teachingsUpdateManyWithWhereWithoutChaptersInput | Prisma.teachingsUpdateManyWithWhereWithoutChaptersInput[]
  deleteMany?: Prisma.teachingsScalarWhereInput | Prisma.teachingsScalarWhereInput[]
}

export type teachingsUncheckedUpdateManyWithoutChaptersNestedInput = {
  create?: Prisma.XOR<Prisma.teachingsCreateWithoutChaptersInput, Prisma.teachingsUncheckedCreateWithoutChaptersInput> | Prisma.teachingsCreateWithoutChaptersInput[] | Prisma.teachingsUncheckedCreateWithoutChaptersInput[]
  connectOrCreate?: Prisma.teachingsCreateOrConnectWithoutChaptersInput | Prisma.teachingsCreateOrConnectWithoutChaptersInput[]
  upsert?: Prisma.teachingsUpsertWithWhereUniqueWithoutChaptersInput | Prisma.teachingsUpsertWithWhereUniqueWithoutChaptersInput[]
  createMany?: Prisma.teachingsCreateManyChaptersInputEnvelope
  set?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  disconnect?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  delete?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  connect?: Prisma.teachingsWhereUniqueInput | Prisma.teachingsWhereUniqueInput[]
  update?: Prisma.teachingsUpdateWithWhereUniqueWithoutChaptersInput | Prisma.teachingsUpdateWithWhereUniqueWithoutChaptersInput[]
  updateMany?: Prisma.teachingsUpdateManyWithWhereWithoutChaptersInput | Prisma.teachingsUpdateManyWithWhereWithoutChaptersInput[]
  deleteMany?: Prisma.teachingsScalarWhereInput | Prisma.teachingsScalarWhereInput[]
}

export type teachingsCreateWithoutChaptersInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type teachingsUncheckedCreateWithoutChaptersInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type teachingsCreateOrConnectWithoutChaptersInput = {
  where: Prisma.teachingsWhereUniqueInput
  create: Prisma.XOR<Prisma.teachingsCreateWithoutChaptersInput, Prisma.teachingsUncheckedCreateWithoutChaptersInput>
}

export type teachingsCreateManyChaptersInputEnvelope = {
  data: Prisma.teachingsCreateManyChaptersInput | Prisma.teachingsCreateManyChaptersInput[]
  skipDuplicates?: boolean
}

export type teachingsUpsertWithWhereUniqueWithoutChaptersInput = {
  where: Prisma.teachingsWhereUniqueInput
  update: Prisma.XOR<Prisma.teachingsUpdateWithoutChaptersInput, Prisma.teachingsUncheckedUpdateWithoutChaptersInput>
  create: Prisma.XOR<Prisma.teachingsCreateWithoutChaptersInput, Prisma.teachingsUncheckedCreateWithoutChaptersInput>
}

export type teachingsUpdateWithWhereUniqueWithoutChaptersInput = {
  where: Prisma.teachingsWhereUniqueInput
  data: Prisma.XOR<Prisma.teachingsUpdateWithoutChaptersInput, Prisma.teachingsUncheckedUpdateWithoutChaptersInput>
}

export type teachingsUpdateManyWithWhereWithoutChaptersInput = {
  where: Prisma.teachingsScalarWhereInput
  data: Prisma.XOR<Prisma.teachingsUpdateManyMutationInput, Prisma.teachingsUncheckedUpdateManyWithoutChaptersInput>
}

export type teachingsScalarWhereInput = {
  AND?: Prisma.teachingsScalarWhereInput | Prisma.teachingsScalarWhereInput[]
  OR?: Prisma.teachingsScalarWhereInput[]
  NOT?: Prisma.teachingsScalarWhereInput | Prisma.teachingsScalarWhereInput[]
  id?: Prisma.StringFilter<"teachings"> | string
  videoId?: Prisma.StringFilter<"teachings"> | string
  duration?: Prisma.IntFilter<"teachings"> | number
  order?: Prisma.IntFilter<"teachings"> | number
  chapterId?: Prisma.StringFilter<"teachings"> | string
  createdAt?: Prisma.DateTimeFilter<"teachings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"teachings"> | Date | string
}

export type teachingsCreateManyChaptersInput = {
  id: string
  videoId: string
  duration: number
  order?: number
  createdAt?: Date | string
  updatedAt: Date | string
}

export type teachingsUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type teachingsUncheckedUpdateWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type teachingsUncheckedUpdateManyWithoutChaptersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  videoId?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type teachingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teachings"]>

export type teachingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teachings"]>

export type teachingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teachings"]>

export type teachingsSelectScalar = {
  id?: boolean
  videoId?: boolean
  duration?: boolean
  order?: boolean
  chapterId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type teachingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "videoId" | "duration" | "order" | "chapterId" | "createdAt" | "updatedAt", ExtArgs["result"]["teachings"]>
export type teachingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}
export type teachingsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}
export type teachingsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapters?: boolean | Prisma.chaptersDefaultArgs<ExtArgs>
}

export type $teachingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "teachings"
  objects: {
    chapters: Prisma.$chaptersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    videoId: string
    duration: number
    order: number
    chapterId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["teachings"]>
  composites: {}
}

export type teachingsGetPayload<S extends boolean | null | undefined | teachingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$teachingsPayload, S>

export type teachingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<teachingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TeachingsCountAggregateInputType | true
  }

export interface teachingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['teachings'], meta: { name: 'teachings' } }
  /**
   * Find zero or one Teachings that matches the filter.
   * @param {teachingsFindUniqueArgs} args - Arguments to find a Teachings
   * @example
   * // Get one Teachings
   * const teachings = await prisma.teachings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends teachingsFindUniqueArgs>(args: Prisma.SelectSubset<T, teachingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Teachings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {teachingsFindUniqueOrThrowArgs} args - Arguments to find a Teachings
   * @example
   * // Get one Teachings
   * const teachings = await prisma.teachings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends teachingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, teachingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Teachings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {teachingsFindFirstArgs} args - Arguments to find a Teachings
   * @example
   * // Get one Teachings
   * const teachings = await prisma.teachings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends teachingsFindFirstArgs>(args?: Prisma.SelectSubset<T, teachingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Teachings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {teachingsFindFirstOrThrowArgs} args - Arguments to find a Teachings
   * @example
   * // Get one Teachings
   * const teachings = await prisma.teachings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends teachingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, teachingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Teachings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {teachingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Teachings
   * const teachings = await prisma.teachings.findMany()
   * 
   * // Get first 10 Teachings
   * const teachings = await prisma.teachings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const teachingsWithIdOnly = await prisma.teachings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends teachingsFindManyArgs>(args?: Prisma.SelectSubset<T, teachingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Teachings.
   * @param {teachingsCreateArgs} args - Arguments to create a Teachings.
   * @example
   * // Create one Teachings
   * const Teachings = await prisma.teachings.create({
   *   data: {
   *     // ... data to create a Teachings
   *   }
   * })
   * 
   */
  create<T extends teachingsCreateArgs>(args: Prisma.SelectSubset<T, teachingsCreateArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Teachings.
   * @param {teachingsCreateManyArgs} args - Arguments to create many Teachings.
   * @example
   * // Create many Teachings
   * const teachings = await prisma.teachings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends teachingsCreateManyArgs>(args?: Prisma.SelectSubset<T, teachingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Teachings and returns the data saved in the database.
   * @param {teachingsCreateManyAndReturnArgs} args - Arguments to create many Teachings.
   * @example
   * // Create many Teachings
   * const teachings = await prisma.teachings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Teachings and only return the `id`
   * const teachingsWithIdOnly = await prisma.teachings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends teachingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, teachingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Teachings.
   * @param {teachingsDeleteArgs} args - Arguments to delete one Teachings.
   * @example
   * // Delete one Teachings
   * const Teachings = await prisma.teachings.delete({
   *   where: {
   *     // ... filter to delete one Teachings
   *   }
   * })
   * 
   */
  delete<T extends teachingsDeleteArgs>(args: Prisma.SelectSubset<T, teachingsDeleteArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Teachings.
   * @param {teachingsUpdateArgs} args - Arguments to update one Teachings.
   * @example
   * // Update one Teachings
   * const teachings = await prisma.teachings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends teachingsUpdateArgs>(args: Prisma.SelectSubset<T, teachingsUpdateArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Teachings.
   * @param {teachingsDeleteManyArgs} args - Arguments to filter Teachings to delete.
   * @example
   * // Delete a few Teachings
   * const { count } = await prisma.teachings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends teachingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, teachingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Teachings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {teachingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Teachings
   * const teachings = await prisma.teachings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends teachingsUpdateManyArgs>(args: Prisma.SelectSubset<T, teachingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Teachings and returns the data updated in the database.
   * @param {teachingsUpdateManyAndReturnArgs} args - Arguments to update many Teachings.
   * @example
   * // Update many Teachings
   * const teachings = await prisma.teachings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Teachings and only return the `id`
   * const teachingsWithIdOnly = await prisma.teachings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends teachingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, teachingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Teachings.
   * @param {teachingsUpsertArgs} args - Arguments to update or create a Teachings.
   * @example
   * // Update or create a Teachings
   * const teachings = await prisma.teachings.upsert({
   *   create: {
   *     // ... data to create a Teachings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Teachings we want to update
   *   }
   * })
   */
  upsert<T extends teachingsUpsertArgs>(args: Prisma.SelectSubset<T, teachingsUpsertArgs<ExtArgs>>): Prisma.Prisma__teachingsClient<runtime.Types.Result.GetResult<Prisma.$teachingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Teachings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {teachingsCountArgs} args - Arguments to filter Teachings to count.
   * @example
   * // Count the number of Teachings
   * const count = await prisma.teachings.count({
   *   where: {
   *     // ... the filter for the Teachings we want to count
   *   }
   * })
  **/
  count<T extends teachingsCountArgs>(
    args?: Prisma.Subset<T, teachingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TeachingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Teachings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeachingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TeachingsAggregateArgs>(args: Prisma.Subset<T, TeachingsAggregateArgs>): Prisma.PrismaPromise<GetTeachingsAggregateType<T>>

  /**
   * Group by Teachings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {teachingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends teachingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: teachingsGroupByArgs['orderBy'] }
      : { orderBy?: teachingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, teachingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTeachingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the teachings model
 */
readonly fields: teachingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for teachings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__teachingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chapters<T extends Prisma.chaptersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.chaptersDefaultArgs<ExtArgs>>): Prisma.Prisma__chaptersClient<runtime.Types.Result.GetResult<Prisma.$chaptersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the teachings model
 */
export interface teachingsFieldRefs {
  readonly id: Prisma.FieldRef<"teachings", 'String'>
  readonly videoId: Prisma.FieldRef<"teachings", 'String'>
  readonly duration: Prisma.FieldRef<"teachings", 'Int'>
  readonly order: Prisma.FieldRef<"teachings", 'Int'>
  readonly chapterId: Prisma.FieldRef<"teachings", 'String'>
  readonly createdAt: Prisma.FieldRef<"teachings", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"teachings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * teachings findUnique
 */
export type teachingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * Filter, which teachings to fetch.
   */
  where: Prisma.teachingsWhereUniqueInput
}

/**
 * teachings findUniqueOrThrow
 */
export type teachingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * Filter, which teachings to fetch.
   */
  where: Prisma.teachingsWhereUniqueInput
}

/**
 * teachings findFirst
 */
export type teachingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * Filter, which teachings to fetch.
   */
  where?: Prisma.teachingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of teachings to fetch.
   */
  orderBy?: Prisma.teachingsOrderByWithRelationInput | Prisma.teachingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for teachings.
   */
  cursor?: Prisma.teachingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` teachings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` teachings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of teachings.
   */
  distinct?: Prisma.TeachingsScalarFieldEnum | Prisma.TeachingsScalarFieldEnum[]
}

/**
 * teachings findFirstOrThrow
 */
export type teachingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * Filter, which teachings to fetch.
   */
  where?: Prisma.teachingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of teachings to fetch.
   */
  orderBy?: Prisma.teachingsOrderByWithRelationInput | Prisma.teachingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for teachings.
   */
  cursor?: Prisma.teachingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` teachings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` teachings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of teachings.
   */
  distinct?: Prisma.TeachingsScalarFieldEnum | Prisma.TeachingsScalarFieldEnum[]
}

/**
 * teachings findMany
 */
export type teachingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * Filter, which teachings to fetch.
   */
  where?: Prisma.teachingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of teachings to fetch.
   */
  orderBy?: Prisma.teachingsOrderByWithRelationInput | Prisma.teachingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing teachings.
   */
  cursor?: Prisma.teachingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` teachings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` teachings.
   */
  skip?: number
  distinct?: Prisma.TeachingsScalarFieldEnum | Prisma.TeachingsScalarFieldEnum[]
}

/**
 * teachings create
 */
export type teachingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * The data needed to create a teachings.
   */
  data: Prisma.XOR<Prisma.teachingsCreateInput, Prisma.teachingsUncheckedCreateInput>
}

/**
 * teachings createMany
 */
export type teachingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many teachings.
   */
  data: Prisma.teachingsCreateManyInput | Prisma.teachingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * teachings createManyAndReturn
 */
export type teachingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * The data used to create many teachings.
   */
  data: Prisma.teachingsCreateManyInput | Prisma.teachingsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * teachings update
 */
export type teachingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * The data needed to update a teachings.
   */
  data: Prisma.XOR<Prisma.teachingsUpdateInput, Prisma.teachingsUncheckedUpdateInput>
  /**
   * Choose, which teachings to update.
   */
  where: Prisma.teachingsWhereUniqueInput
}

/**
 * teachings updateMany
 */
export type teachingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update teachings.
   */
  data: Prisma.XOR<Prisma.teachingsUpdateManyMutationInput, Prisma.teachingsUncheckedUpdateManyInput>
  /**
   * Filter which teachings to update
   */
  where?: Prisma.teachingsWhereInput
  /**
   * Limit how many teachings to update.
   */
  limit?: number
}

/**
 * teachings updateManyAndReturn
 */
export type teachingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * The data used to update teachings.
   */
  data: Prisma.XOR<Prisma.teachingsUpdateManyMutationInput, Prisma.teachingsUncheckedUpdateManyInput>
  /**
   * Filter which teachings to update
   */
  where?: Prisma.teachingsWhereInput
  /**
   * Limit how many teachings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * teachings upsert
 */
export type teachingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * The filter to search for the teachings to update in case it exists.
   */
  where: Prisma.teachingsWhereUniqueInput
  /**
   * In case the teachings found by the `where` argument doesn't exist, create a new teachings with this data.
   */
  create: Prisma.XOR<Prisma.teachingsCreateInput, Prisma.teachingsUncheckedCreateInput>
  /**
   * In case the teachings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.teachingsUpdateInput, Prisma.teachingsUncheckedUpdateInput>
}

/**
 * teachings delete
 */
export type teachingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
  /**
   * Filter which teachings to delete.
   */
  where: Prisma.teachingsWhereUniqueInput
}

/**
 * teachings deleteMany
 */
export type teachingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which teachings to delete
   */
  where?: Prisma.teachingsWhereInput
  /**
   * Limit how many teachings to delete.
   */
  limit?: number
}

/**
 * teachings without action
 */
export type teachingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the teachings
   */
  select?: Prisma.teachingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the teachings
   */
  omit?: Prisma.teachingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.teachingsInclude<ExtArgs> | null
}
