
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/chapters'
export type * from './models/entrance_exams'
export type * from './models/exam_answers'
export type * from './models/exam_questions'
export type * from './models/exams'
export type * from './models/lessons'
export type * from './models/purchases'
export type * from './models/sessions'
export type * from './models/teachings'
export type * from './models/users'
export type * from './commonInputTypes'